### ISSUE TITLE
from_client_secrets_file() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by mateocam** [googleads/google-ads-python#10]
I keep getting this error and I don't know why.

First I copy pasted your code from OAuth Web Application Flow : 
```
import google.oauth2.credentials
import google_auth_oauthlib.flow
# Initialize the flow using the client ID and secret downloaded earlier.
flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(
    'client_secret.json',
    scope=['https://www.googleapis.com/auth/adwords'])
# Indicate where the API server will redirect the user after the user completes
# the authorization flow. The redirect URI is required.
flow.redirect_uri = 'https://www.dintdigital.com'
```

After getting the error I changed it to this:

```
import google.oauth2.credentials
from google_auth_oauthlib.flow import Flow
# Initialize the flow using the client ID and secret downloaded earlier.
flow = Flow.from_client_secrets_file(
    'client_secret.json',
    scope=['https://www.googleapis.com/auth/adwords'],
    redirect_uri = ['https://www.dintdigital.com'])
```

and I keep getting the same error. I don't understand why because I am literally giving from_client_secrets_file 3 arguments, not 2 as the error says.

Please help !

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report, and sorry to hear you've been having trouble getting started! It looks like you've discovered a typo in the Wiki, the line should be:

```
# Initialize the flow using the client ID and secret downloaded earlier.
flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(
    'client_secret.json',
    ['https://www.googleapis.com/auth/adwords'])
```

Note that the `scope` keyword argument was removed. This caused the error you reported because [the method](https://github.com/GoogleCloudPlatform/google-auth-library-python-oauthlib/blob/master/google_auth_oauthlib/flow.py#L157) has no such keyword argument. As a result, the `scopes` argument wasn't never provided, causing this error.

I'm going to take another pass through the Wiki to verify that it works as intended, and will leave this open for tracking purposes.

Regards,
Mark

**Comment by BenRKarl** [comment]
@msaniscalchi were any other changes necessary as a result of this Issue? If not I'm going to close out the issue.
