### ISSUE TITLE
Issue mutating campaign network targeting settings

### ISSUE THREAD

**Issue by ushimado** [googleads/google-ads-python#11]
An update mutate operation on a campaign which includes just changes to the network_targeting settings (4 booleans) goes successfully through the mutate operation, however upon re-requesting the resource, the changes to the network targeting settings appear to have not taken place.

Campaign is a search campaign, modifying any of the following values has no apparent effect:

```
campaign.network_settings.target_content_network
campaign.network_settings.target_google_search
campaign.network_settings.target_partner_search_network
campaign.network_settings.target_search_network
```

As I said above, the mutate happens successfully and the campaign resource path is returned in the response.  Thanks.

**Comment by msaniscalchi** [comment]
Hello,

Could you provide a trivialized code snippet that can replicate your issue? I'd like to verify that this is a library issue as opposed to an API issue--the latter of which is better triaged via the [Google Ads support forum](https://groups.google.com/forum/#!forum/adwords-api).

One item that comes to mind is that mutate calls would use a FieldMask. You can use any example performing an update as a reference for this--for example, the [update_ad_group.py example](https://github.com/googleads/google-ads-python/blob/master/examples/v0/basic_operations/update_ad_group.py). If the update mask specifying the fields you're modifying is not specified, I would expect your changes to be ignored.

Regards,
Mark

**Comment by ushimado** [comment]
Hi Mark, here's a code snippet, not from production code, but reproduces in the same manner the issue mentioned above (it could very well be an API issue), and actually seems more likely that it would be one, than a client library issue.

```
credentials = Credentials(
  None,
  refresh_token=REFRESH_TOKEN,
  client_id=CLIENT_ID,
  client_secret=CLIENT_SECRET,
  token_uri='https://accounts.google.com/o/oauth2/token'
)
client = GoogleAdsClient(credentials, DEVELOPER_TOKEN)

service = client.get_service('CampaignService')
operation = client.get_type('CampaignOperation')
campaign = campaign_operation.update

campaign.resource_name = 'customers/%s/campaigns/%s' % (CUSTOMER_ID, CAMPAIGN_ID)
campaign.network_settings.target_google_search.value = True
campaign.network_settings.target_search_network.value = True
campaign.network_settings.target_partner_search_network = False
campaign.network_settings.target_content_network = False

# No source message, use all of campaign's fields
field_mask = protobuf_helpers.field_mask(None, campaign)
operation.update_mask.CopyFrom(field_mask)

response = service.mutate_campaigns(CUSTOMER_ID, [operation])
```

**Comment by jradcliff** [comment]
Hi,

Another user pointed out the cause of this issue. In the call to `protobuf_helpers.field_mask`, the first argument passed is `None`.

The `protobuf_helpers` utility handles this case by creating a deep copy of the campaign and then clearing it's values. See [line 291](https://github.com/googleapis/google-cloud-python/blob/master/api_core/google/api_core/protobuf_helpers.py#L291).

Theory is that since the call to `Clear()` sets each of the boolean fields to `False`, the `field_mask` returned does not detect any changes between `campaign` and the clone.

Mark, please confirm, but I think a workaround to this would be to do one of the following:

1.  Create `orig_campaign` as `copy.deepcopy(campaign)` (without a subsequent `Clear()` invocation), and then invoke `field_mask` with the arguments `(orig_campaign, campaign)`.

OR

2.   Manually append the field path for the `False` values to the `field_mask` returned by the helper.

Thanks,
Josh, Google Ads API Team

**Comment by ushimado** [comment]
Hi Josh, after looking at the helper I understand what's going on now.  The field mask doesn't reflect all the values being set on the campaign mutation.  I manually built the mask and the mutate works.  Clear() is not the issue though, if Clear() is not called then original will be a pure copy of modified.  Problem is in identifying which fields were set in the updated object.  For updates, when passing None there is insufficient information to create a diff.  Thank you for the help.

**Comment by ushimado** [comment]
Josh - if an original object exists prior to generating a modified update object then there should be no issue with generating the diff.  Depending on a user's specific workflow this may be easy or difficult, however it will make mutating the object possible.  Sorry I misinterpreted your comment above, thanks for the clarification.
