### ISSUE TITLE
"A mutate action is not allowed on this campaign..." using add_keywords.py

### ISSUE THREAD

**Issue by eranShavit** [googleads/google-ads-python#116]
Hi guys,

When trying to run the add_keywords.py example, I'm getting the following error - 
	Error with message "A mutate action is not allowed on this campaign, from this client.".
		On field: operations

This happens while other add_*.py examples are working.

How come some 'add' requests are working and some not?
Is it a configuration setting on my google ads account?

Thanks in advance.

**Comment by BenRKarl** [comment]
Hi @eranShavit thanks for the question - could you share the full error log you're getting?

**Comment by eranShavit** [comment]
Hi there,

See error below - 
Erans-MacBook-Pro:basic_operations eranshavit$ python add_keywords.py -c 8731075499 -a 68212654017 -k eran
No handlers could be found for logger "google.ads.google_ads.client"
Request with ID "Onryd_ozwC7IjSCYxGm6ng" failed with status "INVALID_ARGUMENT" and includes the following errors:
	Error with message "A mutate action is not allowed on this campaign, from this client.".
		On field: operations

**Comment by bfelbo** [comment]
@eranShavit  Did you ever find a solution?

**Comment by BenRKarl** [comment]
Hi All - this is most likely due to the authenticated requester not having permission to mutate the given campaign. By authenticating as a different account, using a [`login-customer-id`](https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid), or mutating a different campaign you should be able to get around it. Feel free to reopen this if you're still having issues.
