### ISSUE TITLE
customer_extension_setting is not created when Feed added through API

### ISSUE THREAD

**Issue by j-walker23** [googleads/google-ads-python#154]
Overall, I am trying to use part of Feeds API documented in Release Notes https://developers.google.com/google-ads/api/docs/release-notes#130_2019-05-22.

When doing an update to ExtensionFeedItem.targeted_campaign, I get below error.
FeedMapping.MULTIPLE_MAPPINGS_FOR_PLACEHOLDER_TYPE.

I noticed when creating a Feed through the api, my account does not have a `customer_extension_setting`.

But when creating a Feed through the UI. It does.
So when trying to create that first, this is the response.

<img width="774" alt="Screen Shot 2019-07-16 at 11 03 06 AM" src="https://user-images.githubusercontent.com/2018885/61314252-7ed22380-a7b9-11e9-86b0-775e40ba3b17.png">

**Comment by BenRKarl** [comment]
Hi @j-walker23 thank you for posting this question. I checked on this request since you received an "unimplemented" error code the actual underlying error is: `CANNOT_MODIFY_LOCATION_CUSTOMER_EXTENSION_SETTING`

This issue does appear to be related to the API, however, and not this library, so would you mind posting a follow up question to the [support forum](https://groups.google.com/forum/#!forum/adwords-api)? That forum is much better equipped to address issues such as this. Thank you!
