### ISSUE TITLE
Add Support for Proxies 

### ISSUE THREAD

**Issue by BenRKarl** [googleads/google-ads-python#171]
This library should offer proxy support in a [similar fashion](https://github.com/googleads/googleads-python-lib/blob/master/googleads.yaml#L104) to the [AdWords client library](https://github.com/googleads/googleads-python-lib).

**Comment by drinkinginthesky** [comment]
so the lib doesn't support proxy yet?

**Comment by BenRKarl** [comment]
@drinkinginthesky no not yet, but we have plans to add it in the future.

**Comment by drinkinginthesky** [comment]
do you have a plan and when will it be done?

**Comment by BenRKarl** [comment]
Unfortunately we don't have a specific timeline, but once we can get a PR up for it I'll link to this issue so you can know when it's available.

**Comment by drinkinginthesky** [comment]
@BenRKarl ok, thanks

**Comment by quba** [comment]
Hi guys,

it turned out that it's even hard to create a workaround for that. Are there any updates on this topic?

**Comment by zaan** [comment]
Hi, in the first place I want to thank you for a great job with the library. Our team is using it with great success, it does the job for us. Lack of support for the proxy is the only thing that we're missing so I just want to put my +1 to that feature request. We offer in our product the Google Ads integration and some of our clients require connection via proxy. There are no reasonable alternatives we could use so as long as the library doesn't support it, our clients cannot download the data which is pretty bad. I would appreciate it a lot if you could put it on the roadmap. Thanks in advance!

**Comment by jvitornf** [comment]
Hi, in the first place I want to thank you for a great job with the library. I used it to test an automation to download data from google ads on my personal device, it works fine. Lack of support for the proxy is the only thing that i'm missing because I have to use this automation on my work device that requires connection via proxy. I tried a lot any alternatives but noone works using python in google APIs. Now I'm trying to use PHP or PERL liberary to take this automation, but I don't know these languages. Please help me and python users.

**Comment by jvitornf** [comment]
Some alternatives that I tried: Selenium webdriver / Google Sheets connection + API to export etc. Other Ads players make those things much easier with http urls using access tokens. Google is making things difficult using much burocracy in this case.

**Comment by BenRKarl** [comment]
We just added proxy support with #405 

Should get published to PyPi in the near future. Closing this for now.
