### ISSUE TITLE
Field mask using protobuf_helpers leaves out path

### ISSUE THREAD

**Issue by JamesBolandDing** [googleads/google-ads-python#192]
Hi,

I'm trying to use this library to switch bidding strategies on campaigns. When I try switching to Manual CPC the `protobuf_helpers.field_mask` to seems to drop the "manual_cpc.enhanced_cpc_enabled" path, resulting in no change at all. 

I know we can add the path in anyway but it makes things a lot tidier if `protobuf_helpers.field_mask` handled this case as nicely as it handles everything else I've given it. 

Also, it might be useful to have an example or two where we see how to create/modify a field mask rather than just having it inferred, just in case there are other examples of this issue.

Thanks!

Sample code:
````
def switch_campaign_bidding_strategy(client, campaign_resource_name, new_bidding_strategy, default_cpa_bid=5.0):
    campaign_operation = client.get_type('CampaignOperation', version='v2')
    campaign = campaign_operation.update

    campaign.resource_name = campaign_resource_name

    if new_bidding_strategy == "MANUAL_CPC":
        campaign.manual_cpc.enhanced_cpc_enabled.value = False
    elif new_bidding_strategy == "ENHANCED_CPC":
        campaign.manual_cpc.enhanced_cpc_enabled.value = True
    elif new_bidding_strategy == "TARGET_CPA":
        campaign.target_cpa.target_cpa_micros.value = int(default_cpa_bid * 1e6)

    field_mask = protobuf_helpers.field_mask(None, campaign)
    
    # The next two lines were added to fix the issue. Without them the manual cpc path is left out of the mask.
    if new_bidding_strategy == "MANUAL_CPC" and "manual_cpc.enhanced_cpc_enabled" not in field_mask.paths:
        field_mask.paths.append("manual_cpc.enhanced_cpc_enabled")

    campaign_operation.update_mask.CopyFrom(field_mask)

    return campaign_operation
````

**Comment by wihl** [comment]
James, Thanks for your note.

There is an example of using field masks in Python in the [docs](https://developers.google.com/google-ads/api/docs/client-libs/python/field-masks). 

Wrt having to also specify eCPC, I'll look into this (and leave the issue open for now).

**Comment by JamesBolandDing** [comment]
Thank you very much for looking into it. Your response time is quite impressive too.

Regarding the examples: I think I may have been a little unclear in my first comment. As you said, there are plenty of examples of using field masks in the docs. However, I haven't seen any examples where you add extra paths to a field mask or create them from scratch.

I realise that this particular example is an outlier, but I thought it might be a nice addition to have something extra for some unforeseen circumstance. I don't have a particular use case in mind however.

**Comment by wihl** [comment]
@JamesBolandDing Is there anything left to do with this issue? If not, then please close it.

**Comment by JamesBolandDing** [comment]
@wihl You said you'd look into why we have to manually add the enhanced_cpc_enabled path. Did anything come from that?

**Comment by BenRKarl** [comment]
@JamesBolandDing jumping in on this issue, you need to manually add the `"manual_cpc.enhanced_cpc_enabled"` field to the field mask because earlier in the code snippet you set the value of the field to `False`, which is the default value for any [`BoolValue`](https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/well-known-types/bool-value) types.

The function `protobuf_helpers.field_mask` takes two message instances, compares them, and returns a list of fields that represent the delta between them. When you pass `None` as the first parameter the function compares the instance to a default instance, so it doesn't recognize that you've updated the `enhanced_cpc_enabled.value` because it's `False` in both cases.

Hope that clarifies! Feel free to re-open this if you have further questions.
