### ISSUE TITLE
Minimum python version support

### ISSUE THREAD

**Issue by yunstanford** [googleads/google-ads-python#197]
Any reason for bumping up minimum support python version so aggressively >= 3.7 ? 
Python 3.6 is still widely being used.

**Comment by wihl** [comment]
The Google Ads API has a very large object model. In order to improve load time performance, we have implemented lazy loading so only the necessary classes are loaded as per [PEP 562](https://www.python.org/dev/peps/pep-0562/) which is specific to Python 3.7+. You can stay with v4.0.0 of this library if don't want to upgrade to 3.7 just yet. There are no functional differences.

**Comment by yunstanford** [comment]
It won't work unless it's LTS, which will accept bugfixes and patches. @wihl

**Comment by wihl** [comment]
PEP 562 was [accepted](https://mail.python.org/pipermail/python-dev/2017-December/151033.html) marked as final, and assigned to Python 3.7. The [LTS Policy](https://www.python.org/dev/peps/pep-0602/#long-term-support-releases) defines v3.7 as a LTS version.

@yunstanford Why do you believe that this is not LTS?

**Comment by yunstanford** [comment]
@wihl not saying python37, was referring this lib, is`google-ads-python==v4.0.0` LTS version ?

**Comment by wihl** [comment]
Yes, we will support v4.0.0 of this library per our regular support policies.

**Comment by yunstanford** [comment]
thanks, good to know
