### ISSUE TITLE
NameError: name 'six' is not defined

### ISSUE THREAD

**Issue by razvanbalosin** [googleads/google-ads-python#199]
There appears to be a reference to `six` which was removed in a previous commit [Removal of Python 2 support (#188)] in `google/ads/google_ads/v2/services/enums.py`

Which is throwing an error when accessing enums without the client. i.e.

```
from google.ads.google_ads.v2.services.enums import AdvertisingChannelTypeEnum
AdvertisingChannelTypeEnum.AdvertisingChannelType.SEARCH
```

```
File ".../google/ads/google_ads/v2/services/enums.py", line 88, in __getattribute__
    six.exec_(class_def_src, {'enum': enum},
NameError: name 'six' is not defined
```

**Comment by razvanbalosin** [comment]
Documentation lacks a bit around enum usage and I'm just trying to figure out the proper way to work with them.
Should we always use the GoogleAdsClient to handle enums? If so, is this the right approach?

```
For example, on the AdvertisingChannelTypeEnum, SEARCH = 2

# Set enum int value
client.get_type('AdvertisingChannelTypeEnum', version='v2').SEARCH

# Get enum text value from enum int -- get 'SEARCH' from int 2
client.get_type('AdvertisingChannelTypeEnum', version='v2').AdvertisingChannelType.Name(2)

# Get enum int value from text dynamically -- get 2 from 'SEARCH'
getattr(client.get_type('AdvertisingChannelTypeEnum', version='v2').AdvertisingChannelType, 'SEARCH')
```

**Comment by wihl** [comment]
The reference to six is an error, which we will address shortly. The first method is the preferred method that is used in the code examples.

**Comment by j-walker23** [comment]
@wihl just making sure it's not my setup. Has the `six` error been released?

**Comment by wihl** [comment]
It has not been released yet. There is a significant update to this library in a couple of weeks which incorporate this change as well as several other things.

**Comment by j-walker23** [comment]
Very good, thanks for the update.

**Comment by BenRKarl** [comment]
@j-walker23 I'll look into the `six` error, I don't think it was incorporated into the recent releases.

In general it's definitely preferable to use the client to access Enums, as in your second example. The reason is that the code underneath `google.ads.google_ads.v2` is generated and the structure could change, however we'll always make sure the client interface is consistent. 

Also your second snippet on Enum usage is correct. It's clunky but right now that's the best way to access data on Enums. We're working on an improvement to this interface, (see: https://github.com/googleads/google-ads-python/issues/110) and are really eager to get it out because the current interface is definitely awkward.

**Comment by j-walker23** [comment]
@BenRKarl this specific `six` error is fixed for me since the 5.x release

**Comment by BenRKarl** [comment]
@j-walker23 you don't see an error when running the below?:

```
from google.ads.google_ads.v2.services.enums import AdvertisingChannelTypeEnum
AdvertisingChannelTypeEnum.AdvertisingChannelType.SEARCH
```

**Comment by j-walker23** [comment]
@BenRKarl I had updated to v3 before ever trying anything.
I had little to none required code changes to update so it was quick and easy (thank you for that!).

Do you need me to go down to v2 and check?
