### ISSUE TITLE
dependendancy PyYAML <5 seems to have broken pipenv install

### ISSUE THREAD

**Issue by cymox1** [googleads/google-ads-python#22]
specifying a non-existent PyYAML version seems to have broken pipenv locking of dependancies, you can reproduce this with `pipenv install googleads==15.0.2`

Here is what am getting: 
```
Adding googleads to Pipfile's [packages]…
Pipfile.lock (35a056) out of date, updating to (269757)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches pyyaml<5.0,>=4.2b1
Tried: 3.10, 3.10, 3.11, 3.11, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13
Skipped pre-versions: 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 4.2b1, 4.2b2, 4.2b4, 4.2b4, 4.2b4, 4.2b4, 4.2b4
There are incompatible versions in the resolved dependencies
```

**Comment by BenRKarl** [comment]
Hi @cymox1,

Thank you for raising this issue! It does appear that `pipenv` is having trouble installing the newest version of PyYAML. While I investigate this you should be OK to install the previous version of `google-ads`.

Also - just for reference - we're currently maintaining two Python libraries for the AdWords and Google Ads APIs. This repo is for the `google-ads` PyPi package, and the `googleads` PyPi package repo is located [here](https://github.com/googleads/googleads-python-lib).

I created a duplicate issue on that repo, since this issue pertains to both packages.

https://github.com/googleads/googleads-python-lib/issues/363

**Comment by BenRKarl** [comment]
@cymox1 I have a resolution for you - 

It appears as though `pipenv` ignores pre-releases by default. The way `googleads` is configured, only pre-released versions of PyYAML will be downloaded until _they_ release a non-pre-release version. This is intended because earlier versions of PyYAML have a known security flaw.

Until a stable version of PyYAML is available you get work around the installation by providing a `--pre` flag to allow pre-release packages:

```bash
$ pipenv install --pre googleads==15.0.2
```

From the [docs](https://pipenv.readthedocs.io/en/latest/#cmdoption-pipenv-install-pre).
