### ISSUE TITLE
Please run this script google ads api

### ISSUE THREAD

**Issue by trabelsirami** [googleads/google-ads-python#225]
Hello,

I've recently started to discover Adwords APIs.
After finally reaching the last step "Make your first API call", I get the following error :
"Your default encoding, cp1252, is not UTF-8. Please run this script with UTF-8 encoding to avoid errors." at least i found the solution and i underline it with green  but now i m  stock with the blue box it gave me no result also no problem to correct  
![zemzem](https://user-images.githubusercontent.com/39746414/74672420-86bdd000-51ad-11ea-82f5-de60bdb66c56.png)
i don(t know why but when i execute i don't get the  campaigns that i have I've read many issues related to this error. I tried to find other ways to run the scripts to avoid this error. What would you suggest me to do ?

Thank you for your help,

**Comment by wihl** [comment]
This issue is related to the legacy [AdWords API](https://github.com/googleads/googleads-python-lib). If this is still a problem specific to Python, either file an issue in that repository or use the [public forums](https://groups.google.com/forum/#!forum/adwords-api).

As a hint:

1. Check your Python version to be 3.6+ for that library.
1. Put `# -*- coding: utf-8 -*-` at the top of your .py file. See [also](https://docs.python.org/3/howto/unicode.html)
