### ISSUE TITLE
google api steps could't have the result needed

### ISSUE THREAD

**Issue by trabelsirami** [googleads/google-ads-python#226]
Hello everybody,
I've recently started to discover Adwords APIs. I’ve basically done almost all the steps i’ve send a request for a developer token and they respond after 4 days i have created a test account with test campaigns after creating the account i got the client id and client secret after i have generated the refresh token following the documentation with this command in blue
![image](https://user-images.githubusercontent.com/39746414/74742793-88e06700-525f-11ea-8537-afcb916dfccc.png)
  ‘$ python generate_refresh_token.py --client_id INSERT_CLIENT_ID --client_secret INSERT_CLIENT_SECRET’
And i did the oauth2 authentication and i have completed the googleads.yaml file with the necessary keys and the json file path 
![image](https://user-images.githubusercontent.com/39746414/74742807-9138a200-525f-11ea-8833-43182e0effcc.png)
And the last step is oppening the file get_campaigns.py and execute it so that it can generate  me the campaigns i did in my test account but in stead it gives me a lot of errors and to insert the developer token even though it’s a test account  
After finally reaching the last step "Make your first API call", I get the following error 
![image](https://user-images.githubusercontent.com/39746414/74742824-9ac20a00-525f-11ea-8d39-895913596961.png)
Please if anyone have a solution or he have worked with google api comment or send me an e mail to trabelsiramii@gmail.com 
Thank you for your help.

**Comment by wihl** [comment]
This issue is related to the legacy [AdWords API](https://github.com/googleads/googleads-python-lib). If this is still a problem specific to Python, either file an issue in that repository or use the [public forums](https://groups.google.com/forum/#!forum/adwords-api). This is the second time you've used the incorrect repository. Please use the appropriate GitHub repository or we may not respond to your future questions.

Based on the error message, you've haven't filled in the [Developer Token](https://developers.google.com/adwords/api/docs/guides/first-api-call#developer_token).

**Comment by trabelsirami** [comment]
ok thank you wihl can you give me your email because this is my first time with the google ads api and i m really confused so if you can give me your email so i can talk to you directly and thank you a lot 
my e-mail is trabelsiramii@gmail.com

**Comment by wihl** [comment]
Sorry, can't do that per Google policies. Please use the above entry points.
