### ISSUE TITLE
How "include brand name in results" in keyword planner?

### ISSUE THREAD

**Issue by ahvahsky2008** [googleads/google-ads-python#233]
I dont find this property in lib.
![image](https://user-images.githubusercontent.com/8035828/75623634-f627bc80-5bbc-11ea-9411-00567dec971e.png)

**Comment by wihl** [comment]
What type of campaign / ad are inquiring about? For example Responsive Search Ads has https://developers.google.com/google-ads/api/fields/v2/ad_group_ad#ad_group_ad.ad.responsive_display_ad.business_name

**Comment by wihl** [comment]
I re-read your subject and see what you are referring to. Correct, this feature does not exist in [this API](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v3.services#generatekeywordideasrequest) or the previous legacy [AdWords API](https://developers.google.com/adwords/api/docs/reference/v201809/TargetingIdeaService.Type_AttributeMapEntry). I don't know when or if it will appear (and couldn't promise here anyway). You'll have to check in future releases to see when it will appear. Since this issue is not specific to Python, I'm closing the issue.

**Comment by wihl** [comment]
Internal ref: b/150950301
