### ISSUE TITLE
Problem with `TargetRestrictionOperation` and `FeedAttributeOperation` enums

### ISSUE THREAD

**Issue by henribru** [googleads/google-ads-python#267]
There seems to still be a few problems with the `enums.py` files after the recent fix. Specifically, dynamically creating the enums for `TargetRestrictionOperation` and `FeedAttributeOperation` in the v3 version fail because the name of the inner class in the string is different from the class attribute they're stored in (triggering an assertion error in `_CreateEnumTypeUponFirstAccess.__getattribute__`), while in the v2 version `FeedAttributeOperation` fails because of incorrect indentation inside the string.

**Comment by BenRKarl** [comment]
@henribru thanks for pointing this out - how are you triggering these errors? By importing the enum directly or by using `get_type`?

**Comment by henribru** [comment]
I'm importing them directly. As far as I can tell you can't actually use `get_type` to import the enums defined in `enums.py`, as `get_type` imports from `types.py` and the `getattr` there imports enums from the protobuf files, not `enums.py`.

```python
>>> from google.ads.google_ads.v3.services.enums import TargetRestrictionOperation, FeedAttributeOperation
>>> TargetRestrictionOperation.TargetRestrictionOperation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/henbruas/.cache/pypoetry/virtualenvs/google-ads-stubs-ACofHr-C-py3.7/lib/python3.7/site-packages/google/ads/google_ads/v3/services/enums.py", line 81, in __getattribute__
    assert class_def_src.startswith('class %s(enum.' % enum_type_name), 'Expected ' + enum_type_name
AssertionError: Expected TargetRestrictionOperation
>>> FeedAttributeOperation.FeedAttributeOperation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/henbruas/.cache/pypoetry/virtualenvs/google-ads-stubs-ACofHr-C-py3.7/lib/python3.7/site-packages/google/ads/google_ads/v3/services/enums.py", line 81, in __getattribute__
    assert class_def_src.startswith('class %s(enum.' % enum_type_name), 'Expected ' + enum_type_name
AssertionError: Expected FeedAttributeOperation
>>> from google.ads.google_ads.v2.services.enums import FeedAttributeOperation
>>> FeedAttributeOperation.Operator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/henbruas/.cache/pypoetry/virtualenvs/google-ads-stubs-ACofHr-C-py3.7/lib/python3.7/site-packages/google/ads/google_ads/v2/services/enums.py", line 90, in __getattribute__
    object.__getattribute__(self, '__dict__'))
  File "<string>", line 9
    """
      ^
IndentationError: expected an indented block
```

**Comment by BenRKarl** [comment]
Ok got it - so the safest thing to do is to use `get_type` to import those types.  It's very likely the code below the `v3` dir will change in the future since it's generated code, so importing anything there isn't very safe, unfortunately. I know it's counterintuitive not to be able to use `import` like that.

With that said, `'TargetRestrictionOperation'` and `'FeedAttributeOperation'` aren't enums, so I'm not sure why they're in that `enums.py` file in the first place. If you want to import those types directly you can use:

```python
from google.ads.google_ads.v3.proto.common.targeting_setting_pb2 import TargetRestrictionOperation
from google.ads.google_ads.v3.proto.resources.feed_pb2 import FeedAttributeOperation
```

I'll look into the issues you mention in those files, meanwhile let me know if neither of the above import mechanisms do the trick for you. 

And for reference if you want to know where in the tree a type is located the best place to start is with the source proto files for Ads, which are located [here](https://github.com/googleapis/googleapis/tree/master/google/ads/googleads). The generated code here _mostly_ mirrors the structure over there.

**Comment by henribru** [comment]
I assume the reason they're in `enums.py` is that while `TargetRestrictionOperation` and `FeedAttributeOperation` aren't enums, `TargetRestrictionOperation.Operator` and `FeedAttributeOperation.Operator` are. It seems like the attribute for the inner enum class in these is merely named incorrectly in v3's `enums.py` (for v2's file, `FeedAttributeOperation` is named `Operator`, consistent with the protobuffer).

I realize that importing like this isn't officially supported. Like I mentioned when reporting an issue previously I'm creating type stubs for the library, which unfortunately does make me have to depend on the internal structure of the code. But I'll live with the fact that changes to it will require changes to my stubs as well (like your code, my stubs are mostly generated automatically anyway).

Can I ask what actually `enums.py` is for, by the way? You suggest using `get_type` and like I mentioned `get_type` will give you the enums from the compiled protobuffer files. For example, `get_type("AdGroupTypeEnum")` imports from `proto/enums/ad_group_type_pb2.py`, not `services/enums.py`. `enums.py` seems to reimplement all the enums generated from the protobuffers as "native" Python enums, but I don't see them being used anywhere and users of the library won't get them without using unsupported importing, so I'm a bit confused about what their purpose is currently.

**Comment by BenRKarl** [comment]
@henribru that's a great question, I'm actually not 100% sure what that file is used for. My initial assumption was that the other generated services files depended on it, but as you mentioned it doesn't actually appear to be used elsewhere in the codebase. It's _possible_ that it's a relic from an early iteration of the library and was intended to be used in a certain way that never transpired. I'm going to spend some time investigating and will make some changes if necessary. I'll follow up here with any details I discover.

**Comment by BenRKarl** [comment]
@henribru Ok so after some investigating I discovered the purpose of `services/enums.py` and it made me aware of some functionality in the library I didn't even know existed. You can see in the top-level [`__init__.py`](https://github.com/googleads/google-ads-python/blob/master/google/ads/google_ads/v3/__init__.py#L265) file for each version `enums` is added to each service client module that's imported. So, instead of importing Enums using the `client.get_type` method you can access them on a service client directly, like this:

```python
ga_client = client.get_service('GoogleAdsService', version='v3')
ad_group_status = ga_client.enums.AdGroupStatusEnum.AdGroupStatus.PAUSED
```

The Enums you pointed out above are still problematic, so we need to investigate them and post a fix. Once that's done I believe we'll want to update all of our examples to use this improved interface as well.

Thanks again for pointing this out!
