### ISSUE TITLE
Google Ads API - Minimum Python Version

### ISSUE THREAD

**Issue by liadbar** [googleads/google-ads-python#284]
About the minimum python version for Google Ads API
As I see it - for Google Ads V3 having python version v3.7 will enable me to run it.
For Google Ads V1, V2 python 3.6+ works.

My questions -
1. Is that correct?
2.  Since upgrading the python version requires changes in our production environments.
If I'll use the V2 for the offline conversion, can I be exposed to risks, or it also ok? 

Thank you!

**Comment by liadbar** [comment]
BTW I'm using the API for upload offline conversion as Google [documentation](https://developers.google.com/google-ads/api/docs/samples/upload-offline-conversion#python)

**Comment by BenRKarl** [comment]
Hi @liadbar the minimum requirement of Python 3.7.0 applies to this library as a whole, including all version v1, v2 and v3. Generally we can't support issues or bug fixes related to compatibility with Python versions less than 3.7.0.

That said you _may_ be safer using v1 than using v2 or v3 because the last two versions use some import logic ([here](https://github.com/googleads/google-ads-python/blob/master/google/ads/google_ads/v2/__init__.py#L244) for example) that requires 3.7.0.

Unfortunately I can't say you won't be exposed to risks by running any portion of the library in 3.6.0.
