### ISSUE TITLE
module 'google.ads.google_ads' has no attribute 'client'

### ISSUE THREAD

**Issue by Cosbgn** [googleads/google-ads-python#3]
I'm trying to use this library to access my clients' data, so authenticating via token and not YAML file.

With the AdWords library I would do something like this:

```
oauth2_client = oauth2.GoogleRefreshTokenClient(GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, refresh_token)
adwords_client = adwords.AdWordsClient(ADWORDS_DEV_TOKEN'], oauth2_client, client_customer_id=aw_account)
service = adwords_client.GetService('CampaignService', version='v201806')
```
Now I'm trying to migrate to this new library and I'm doing something like this:

```
import google
##
credentials = google.oauth2.credentials.Credentials(None,refresh_token = refresh_token,client_id =GOOGLE_CLIENT_ID,client_secret = GOOGLE_CLIENT_SECRET, token_uri = 'https://accounts.google.com/o/oauth2/token')
credentials.refresh(google.auth.transport.requests.Request())
client = google.ads.google_ads.client.GoogleAdsClient(credentials,ADWORDS_DEV_TOKEN)
ga_service = client.get_service('GoogleAdsService')
```
However I get the following error:
`module 'google.ads.google_ads' has no attribute 'client'`
What am I doing wrong?

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! The underlying cause in this case appears to be that we're using [namespace packages](https://packaging.python.org/guides/packaging-namespace-packages) with this library in order to organize Google libraries with a top-level `google` import. We're also going a step further to organize ads libraries under `google.ads`.

However, looking more closely, I think we were a little overzealous in our use of namespace packages in that it doesn't really make sense to apply it to the `google_ads` package. We should change that, which I expect should make the `client` module accessible from `google.ads.google_ads` package. Note though, that you'll then need to import `google.ads.google_ads` rather than just `google` as you do above.

As a work-around for now, you should provide a full import path such as:

```
import google.ads.google_ads.client
...
client = google.ads.google_ads.client.GoogleAdsClient(credentials, ADWORDS_DEV_TOKEN)
...
```

We'll push these changes in an upcoming release.

**Comment by Cosbgn** [comment]
Ok, Thanks! I'm encountering another issue but I'll open a new thread to keep things organized.
