### ISSUE TITLE
googleads-python-lib versus google-ads-python?

### ISSUE THREAD

**Issue by papaben** [googleads/google-ads-python#306]
Hi,

I apologize if this is a dumb question, but I'm trying to figure out the difference between these two packages. Previously, I'd been tracking versions on the sunset page based on a YYYMMDD scheme. Then over the summer the sunset page disappeared. Now, I see that there is a new table of deprecations on the (revived) [sunset page](https://developers.google.com/google-ads/api/docs/sunset-dates) with a whole new versioning scheme along with a new python SDK. It's totally possible that I just haven't done enough research to find my answer, but I was hoping that someone knowledgeable might be able to point me in the right direction? 

Thank you very much.

Sincerely,
Ben

1. https://github.com/googleads/googleads-python-lib
2. https://github.com/googleads/google-ads-python

**Comment by BenRKarl** [comment]
Hey @papaben - not a dumb question at all. We're currently maintaining two different APIs that offer programmatic access to Google Ads. There's the older AdWords API, which is supported by the Python module named googleads-python-lib (`python -m pip install googleads`), and the newer Google Ads API, which is supported by the Python module google-ads-python (`python -m pip install google-ads`). We first announced the Google Ads API [back in 2018](https://ads-developers.googleblog.com/2018/04/join-beta-for-new-adwords-api.html) and have been working to bring it to production ever since.

The two APIs are quite differentl; AdWords uses SOAP and Google Ads uses [protocol buffers](https://developers.google.com/protocol-buffers). We'll be supporting the AdWords API for quite a while still, but will eventually be deprecating it and shifting more resources towards supporting the Google Ads API. I encourage you to start researching the Google Ads API by looking over our [developer documentation](https://developers.google.com/google-ads/api/docs/start) and thinking ahead about migrating.

If you have any questions about this Python module please open an Issue and we'll try to help you out as quickly as possible. However for more general questions about the API, take a look at our [Support Forum](https://groups.google.com/g/adwords-api).

**Comment by papaben** [comment]
Thank you so much for the detailed response!
