### ISSUE TITLE
How can I assign attribute_values to a FeedItemOperation?

### ISSUE THREAD

**Issue by mbaader** [googleads/google-ads-python#326]
Hi, I want to create a new sitefeed item but I'm struggling with assigning the attibute_values to the FeedItemOperation using the Python library for the Google Ads API.

#so far it works:
     feed_item_operation = google_ads_client.get_type(
        'FeedItemOperation', version=VERSION)
      feed_item = feed_item_operation.create
      feed_item.feed = sitefeed_resource_name
#but here I'm lost
      feed_item.attribute_values ...

This ist what it should look like:

`attribute_values: [feed_attribute_id {
  value: 1
}
string_value {
  value: "https://www.domain.com/"
}
]`

Can you help me out?

Regards
Mat

**Comment by BenRKarl** [comment]
@mbaader - with 10.0.0 of this library you can do this:

```py
client = GoogleAdsClient.load_from_storage(version="v6")
feed_item_attr_val = client.get_type("FeedItemAttributeValue")
feed_item_attr_val.feed_attribute_id = 1
feed_item_attr_val.string_value = "https://www.domain.com/"
feed_item.attribute_vales.append(feed_item_attr_val)
```

Since `attribute_values` is a repeated field it behaves like a list now, so you can use `extend` and pass in another existing list, or you can assign a comprehension result. See [these docs](https://developers.google.com/google-ads/api/docs/client-libs/python/library-version-10#repeated_fields) about the new interface for repeated fields.
