### ISSUE TITLE
filtering on segments.device breaks query

### ISSUE THREAD

**Issue by ushimado** [googleads/google-ads-python#36]
query is as follows:

```
SELECT
  segments.date,
  campaign.id,
  segments.ad_network_type,
  campaign.advertising_channel_type,
  campaign.advertising_channel_sub_type,
  metrics.clicks,
  metrics.cost_micros,
  metrics.all_conversions,
  metrics.all_conversions_value,
  metrics.impressions,
  metrics.average_position,
  metrics.conversions,
  metrics.content_impression_share,
  metrics.content_budget_lost_impression_share,
  metrics.content_rank_lost_impression_share,
  metrics.search_impression_share,
  metrics.search_budget_lost_impression_share,
  metrics.search_rank_lost_impression_share
FROM
    campaign
WHERE
    segments.date >= '2019-02-01' AND
    segments.date <= '2019-02-04' AND 
    segments.device IN (MOBILE) AND
    metrics.impressions >= 0
```

the query works properly except for when clause below is present:
`segments.device IN (MOBILE) AND`

the field in question should be selectable as well as filterable.  the error i'm receiving back is not verbose (other errors i've received have been verbose in terms of the logging).  this is what i get:

`InvalidArgument: 400 Request contains an invalid argument.`

i also tried reducing the selected fields to comply with the supported metrics listed in the documentation under segments.device as follows:

```
SELECT
  segments.date,
  campaign.id,
  segments.ad_network_type,
  campaign.advertising_channel_type,
  campaign.advertising_channel_sub_type,
  metrics.clicks,
  metrics.cost_micros,
  metrics.all_conversions,
  metrics.all_conversions_value,
  metrics.impressions,
  metrics.average_position,
  metrics.conversions,
  metrics.search_impression_share,
  metrics.search_budget_lost_impression_share,
  metrics.search_rank_lost_impression_share
FROM
    campaign
WHERE
    segments.date >= '2019-02-01' AND
    segments.date <= '2019-02-04' AND 
    segments.device = MOBILE AND
    metrics.impressions >= 0
```
i'm hoping i haven't missed something in the documentation. i am using v0.7 of the client library

[segments.device documentation](https://developers.google.com/google-ads/api/docs/fields/segments#segmentsdevice)

**Comment by BenRKarl** [comment]
Thanks @ushimado I'll take a look and see if I can help.

**Comment by BenRKarl** [comment]
@ushimado - it looks like three of the metrics in your original query aren't selectable with `segments.devices`:

* `metrics.content_impression_share`
* `metrics.content_budget_lost_impression_share`
* `metrics.content_rank_lost_impression_share`

Some metrics just aren't segmented in certain ways and that appears to be the case here. Hope this helps!

Also if you have logging set up you should be seeing an error similar to the below. [Here](https://github.com/googleads/google-ads-python#enabling-and-configuring-logging) are some instructions to configure logging, if you haven't already done so. 

`Error with message "Cannot select the following segments because at least one unsupported metric is found in SELECT or WHERE clause: 'segments.device'(unsupported metrics: 'content_impression_share', 'content_budget_lost_impression_share', 'content_rank_lost_impression_share').`

**Comment by BenRKarl** [comment]
@ushimado actually I noticed that device does not seem to be incompatible with content impressions share in the old API, so I'm inquiring as to whether there's a reason for the difference, or perhaps whether this is a bug. I'll follow up as soon as I have more information. Thanks!

**Comment by ushimado** [comment]
@BenRKarl thanks for looking into the issue.  in my post i mentioned the 3 fields which you reported as incompatible with the device (see 2nd query).  the problem however was not limited to the removal of those fields.  somehow the query fails regardless of their inclusion.

**Comment by BenRKarl** [comment]
@ushimado Ah I see - the second query is failing for a different reason - it's trying to filter on a field that isn't selected (`segments.device`). If you add `segments.device` to the `SELECT` clause, or remove `segments.device = MOBILE` from the `WHERE` clause it should work. Does that help?

**Comment by ushimado** [comment]
@BenRKarl that indeed did it! so should it be a common assumption that a filtered field in the where clause must also be present in the select clause, or is that limited to segments?  at any rate this solves my immediate issue, thanks for the help there.  let's keep this ticket open though until we confirm the point you mentioned earlier, regarding a potential but with the 3 content_* metrics.  thanks again.

**Comment by ushimado** [comment]
@BenRKarl it occurs to me that the requirement to include the segmentation in the SELECT clause of a given query has some nasty implications for the aggregation of data.  supposing we want to limit the results of a query to 3 device types but not segment the results by said device types, this would necessitate re-aggregation after combing through the results since selecting on the segmentation would segment the results. 

is there a different way to filter on a device (or any segmentation for that matter) without needing to segment by it?  i don't believe inclusion in the requested fields was a requirement in the previous adwords apis.  not sure if this is an api limitation or a client one.  please let me know what you think.  thanks.

**Comment by BenRKarl** [comment]
@ushimado After some investigation I learned that selecting those `metrics` fields along with `segments.device` is functionality that isn't yet part of the API, but it should be added in an upcoming release. If you keep an eye on the [Developer Blog](http://ads-developers.googleblog.com/) you'll be able to catch changes as they're released.

To your other point; the query isn't actually doing any "segmenting" in the traditional SQL sense. You can think of `segments` as a separate table, so there aren't consequences to filtering segmented data. It's required to have that field in the select clause in order to avoid duplicate rows in the response.

Hope that helps! I'm going to close this issue for now. If you have further questions about the API generally those questions are better directed to the [support forum](https://groups.google.com/forum/#!forum/adwords-api).

**Comment by ushimado** [comment]
@BenRKarl thanks a lot for the followup, we really appreciate it. ok, i'm going to wait for a bump in the api and then verify that everything is working as expected. i'll be sure to direct further api related questions to the support forum.
