### ISSUE TITLE
The example "add_customer_match_user_list" hangs forever.

### ISSUE THREAD

**Issue by luongli** [googleads/google-ads-python#360]
I try uploading customer list to my google ads account by following this example but the program hangs forever when I wait for the result of the operation response. I thought that my code has some error at first, so I try to run the original example and get the same problem at line 189. I use python version 3.8.2

https://github.com/googleads/google-ads-python/blob/1fd0cfe963dfaa7c31ae9af89305012a4076c04d/examples/remarketing/add_customer_match_user_list.py#L189

**Comment by nbdaw-st** [comment]
I am facing the same issue here. This weird issue happens when executing all added operations generated from _build_offline_user_data_job_operations function. A typical example for an added operation is:

[create {
  user_identifiers {
    hashed_email {
      value: "xxxx"
    }
  }
  user_identifiers {
    hashed_phone_number {
      value: "xxxx"
    }
  }
}]

And then this operation is further utilized by run_offline_user_data_job. Whenever operation_response.result() starts, the endless server response comes into play. A typical one will be:

Request made: ClientCustomerId: None, Host: googleads.googleapis.com:443, Method: /google.longrunning.Operations/GetOperation, RequestId: xxxx, IsFault: False, FaultMessage: None

Request made: ClientCustomerId: None, Host: googleads.googleapis.com:443, Method: /google.longrunning.Operations/GetOperation, RequestId: xxxx, IsFault: False, FaultMessage: None
.... (keeps populating without an end)

I am currently using the v4 version of the client.

**Comment by luongli** [comment]
I found the solution. Actually, there is no need to wait for the result. operation_response.result() waits for the results of the offline user data job running on google servers. It may take a long time for the job to finish, so the client hangs there. It's fine not to wait for the response and check for the status of the job later using offline_user_data_job_resource_name.

**Comment by nbdaw-st** [comment]
hey @luongli, what did you do to jump out of the loop from operation_response.result()?

**Comment by luongli** [comment]
@nbdaw-st don't call it, operation_response.result() just waits for the response from server (blocking call). You can the same thing without blocking by querying the status of the offline job periodically using GoogleAdsService
