### ISSUE TITLE
trouble running get_account_hierarchy.py example?

### ISSUE THREAD

**Issue by thefrankharvey** [googleads/google-ads-python#364]
Hi I'm trying to run the get_account_heirarchy.py example and I keep running into this error:
Traceback (most recent call last):
  File ".\get_account_hierarchy.py", line 202, in <module>
    main(google_ads_client, args.login_customer_id)
  File ".\get_account_hierarchy.py", line 101, in main
    customer_client.id
  File "C:\Python\Python38\lib\site-packages\google\protobuf\message.py", line 94, in __hash__
    raise TypeError('unhashable object')
TypeError: unhashable object

I'm running this command from the project directory:
python .\get_account_hierarchy.py -l 0123456789

Also, I've tried:
python .\get_account_hierarchy.py --manager_customer_id 0123456789

(the argument is actually our manager account customer id and I do have the yaml file with our creds in the directory)

Could you please tell me what I'm doing wrong?

**Comment by BenRKarl** [comment]
@thefrankharvey thanks for the question - what version of `protobuf` are you using?

**Comment by thefrankharvey** [comment]
Thanks Ben. protobuf-3.12.2.dist-info

**Comment by thefrankharvey** [comment]
@BenRKarl Hey Ben, any luck on this?

**Comment by arammaliachi** [comment]
@BenRKarl @thefrankharvey I was running into the same error.  

I believe the problem is that the `if` statement is checking if `customer_client.id` exists in a dictionary. By default `is in` checks for the keys of a dictionary and keys must be strings, problem is `customer_client.id` is a `<class 'google.protobuf.wrappers_pb2.Int64Value'>` .
