### ISSUE TITLE
How could i get Bid adjustment actual %value from Device level - MOBILE ?

### ISSUE THREAD

**Issue by shailavij** [googleads/google-ads-python#398]
How could i get Bid adjustment actual % value from Adgroup -Device level - MOBILE ?

I have tried to use Python code  from Example folder : 'get_ad_group_bid_modifiers.py' to get bid value , whereas it returns bid in scale value between 1 to 10 instead of percentage .

Its look like this API
![image](https://user-images.githubusercontent.com/49098763/113118742-a83e1780-9207-11eb-9da4-85efd9156cae.png)

Python code Output

![image](https://user-images.githubusercontent.com/49098763/113118642-9197c080-9207-11eb-9b2d-e9f7238c8423.png)

Kindly advice any suggestions or suitable query to get Bid value in Adgroup level.

**Comment by BenRKarl** [comment]
@shailavij I don't believe it's possible to retrieve this value as a percentage. It's returned as a multiplier, which means multiply the current bid value by 0.85, which is the same as reducing it by 15%. To convert this to a percentage amount you would need to convert the multiplier that's returned.

If you have further questions I recommend reaching out to the [support forum](https://support.google.com/google-ads/thread/new), or our [support team](https://support.google.com/google-ads/gethelp), since this is a general API issue they're better equipped to help.
