### ISSUE TITLE
Offline Conversion Upload Example

### ISSUE THREAD

**Issue by MarkMODonnell** [googleads/google-ads-python#407]
Hello, I am looking at a use case of uploading thousands of offline conversions per day. I see in the [documentation](https://developers.google.com/google-ads/api/docs/best-practices/system-limits?hl=en#conversion-upload) that there is a limit of 2,000 operations performed per API call, but the [example](https://github.com/googleads/google-ads-python/blob/589952affe089408a7f9cc64196e8511df08f032/examples/remarketing/upload_offline_conversion.py) in this library only shows how to add a single operation per call. Is there an example available for how to upload multiple offline conversions per call? Thanks!

**Comment by BenRKarl** [comment]
@MarkMODonnell unfortunately we don't have such an example, but doing so wouldn't be much different from what's already shown.

Instead of initializing a `ClickConversion` as a one-off, you could move the logic from line [40](https://github.com/googleads/google-ads-python/blob/589952affe089408a7f9cc64196e8511df08f032/examples/remarketing/upload_offline_conversion.py#L40) to line [50](https://github.com/googleads/google-ads-python/blob/589952affe089408a7f9cc64196e8511df08f032/examples/remarketing/upload_offline_conversion.py#L50) into a loop to create a `list` of conversion objects.

From there you can assign the list to the `conversions` field on the request just like what already happens on line [55](https://github.com/googleads/google-ads-python/blob/589952affe089408a7f9cc64196e8511df08f032/examples/remarketing/upload_offline_conversion.py#L55).

The `conversions` field is a repeated field and supports a number of different ways to add multiple items to it. See our documentation on repeated fields [here](https://developers.google.com/google-ads/api/docs/client-libs/python/library-version-10#repeated_fields).
