### ISSUE TITLE
Keyword plan related questions

### ISSUE THREAD

**Issue by mrn-aglic** [googleads/google-ads-python#431]
Hi, I have two questions related to keyword plans when using the library. 

Is there a way to get all keyword plans created by the account that uses the API?

Is it possible to generate forecast metrics with keyword planner API without creating campaigns? I'd like to input a list of keywords and just get a forecast based on that list. 
As far as I can tell this is possible in the AdWords API using TrafficEstimatorService. 

I have consulted Google docs and the answer to both questions appears bot be a "no", but I want to make sure. Perhaps someone knows of a workaround or I missed some resource.

**Comment by BenRKarl** [comment]
Hi @mrn-aglic - this question is better suited for our [general API support page](https://developers.google.com/google-ads/api/support), but I'll share what I know here in case it's helpful:

* I think you can use a Search request against the [`keyword_plan`](https://developers.google.com/google-ads/api/fields/latest/keyword_plan) report to get a list of all the keyword plans in an account.
* I don't believe it's possible to generate forecast metrics without a campaign, because the service relies on the historical metrics of the campaign.

If you need additional detail I recommend reaching out to one of the support resources in the page I linked above.
