### ISSUE TITLE
[Question] How to get  ad_group_asset data?

### ISSUE THREAD

**Issue by siwwitf** [googleads/google-ads-python#452]
Hi,I am trying get data from ad_group_asset, but it is not returning any value. Program runs, nothing is printed. Meaning there are no results from the query. Yet there are multiple asset on the account which is connected.
 
Python is v3.9.5. Google-ads-python is v12.0.0.

 > ```python
> query = """ 
>    SELECT segments.conversion_action, 
>.     segments.conversion_action_category,
>      segments.conversion_action_name, 
>      metrics.conversions_value, 
>      metrics.conversions, 
>      asset.name, 
>      campaign.name, 
>      ad_group.name 
>      FROM ad_group_asset """
>ga_service = client.get_service("GoogleAdsService")
> response = ga_service.search_stream(customer_id=str(list_row.customer_client.id), query=query)
>   for batch in response:
>      print(batch)
>      for row in batch.results:
>        print(row)
>```
 When I print (response), it returns:
>```python
> <google.api_core.grpc_helpers._StreamingResponseIterator object at 0x7fcc1db183d0>
>```

When I request for campaign_asset or customer_asset,the result is the same.

Thanks.

**Comment by davedavis** [comment]
Hi @siwwitf
The row object contains all the requested row data from the query, so you need to print those individually.

So instead of printing row, print, for example, row.campaign.name etc.

I'd encourage you to look through some of the other examples to see how this is done for other metrics and segments. 

Hope that helps!

**Comment by siwwitf** [comment]
> Hi @siwwitf
> The row object contains all the requested row data from the query, so you need to print those individually.
> 
> So instead of printing row, print, for example, row.campaign.name etc.
> 
> I'd encourage you to look through some of the other examples to see how this is done for other metrics and segments.
> 
> Hope that helps!

**Comment by siwwitf** [comment]
@davedavis  
When I print row.campaign.name etc ,its also nothing.The question is that there are no results from the query.Yet there are multiple asset on the account which is connected.I think, this question is related to google ads api v8.0.

**Comment by davedavis** [comment]
What assets exactly are you looking to retrieve?

**Comment by tuojiangma** [comment]
I have same issue

**Comment by BenRKarl** [comment]
@siwwitf @tuojiangma - can you clarify, is the issue that the `for` loop doesn't execute because the query returns no results from the API? Not that the individual fields on the objects are empty, is that right?

My guess is that this is intended behavior of the `ad_group_asset` resource. Would you please reach out to the [support team](https://developers.google.com/google-ads/api/support) for help, since this doesn't appear to be specific to the Python client library?
