### ISSUE TITLE
CampaignCriterionOperation does not work when bid_modifier value is set to 0.0

### ISSUE THREAD

**Issue by siciarek** [googleads/google-ads-python#478]
I have to reopen https://github.com/googleads/google-ads-python/issues/476

```
When I try to update campaign criterion via CampaignCriterionOperation I run

criterion = operation.update
criterion.resource_name = criterion_resource_name
criterion.bid_modifier = bid_modifier
self.api.update_mask(criterion, operation)
the code works fine when I set values from the 0.1 - 10.0 range

But there are two special values like
0.0 - which sets in google ads panel value -100%
None - which sets the criterion bid_modifier off (remove the field from object) - in google ads panel visible as dash
```

Following your advice I posted the problem on the forum
I am afraid that the problem is lib related. I got an answer from `adsapi`

```
According to this guide, the modifier must be in the range: 0.1 - 10.0.
Most targetable criteria types support modifiers. Use 0 (not 0.0) to opt out of a Device type. 
```

So i triplechecked assignment bid_modifier as 0 (integer value) and just after the assignment it is casted into float.
but zero value is not affected to the update_mask.

**From google client log**

```
Method: /google.ads.googleads.v8.services.CampaignCriterionService/MutateCampaignCriteria
Host: googleads.googleapis.com
Headers: {
  "developer-token": "REDACTED",
  "login-customer-id": "7281957450",
  "x-goog-api-client": "gl-python/3.9.6 grpc/1.39.0 gax/1.31.0 gapic/13.0.0",
  "x-goog-request-params": "customer_id=3783286648"
}
Request: customer_id: "3783286648"
operations {
  update {
    resource_name: "customers/3783286648/campaignCriteria/14178383920~30000"
    bid_modifier: 1.100000023841858
  }
  update_mask {
    paths: "resource_name"
    paths: "bid_modifier"
  }
}
operations {
  update {
    resource_name: "customers/3783286648/campaignCriteria/14178383920~30001"
    bid_modifier: 0.3499999940395355
  }
  update_mask {
    paths: "resource_name"
    paths: "bid_modifier"
  }
}
operations {
  update {
    resource_name: "customers/3783286648/campaignCriteria/14178383920~30002"
    bid_modifier: 0.0
  }
  update_mask {
    paths: "resource_name"
  }
}

```

**Comment by BenRKarl** [comment]
Hi @siciarek, thanks for reporting this! The issue here is that the field mask helper doesn't distinguish between fields that are unset, and fields that are explicitly set to their default value, which, for `bid_modifier`, is `0` because it is a numeric value. See [here](https://developers.google.com/protocol-buffers/docs/proto3#default) for a list of default values for all field types in protobuf. Also see this [open bug](https://github.com/googleapis/python-api-core/issues/232) to get this fixed in the field mask helper. While that's in progress, you will need to explicitly add the field path to the update mask.
