### ISSUE TITLE
New required `use_proto_plus` parameter in version `14.0.0`

### ISSUE THREAD

**Issue by BenRKarl** [googleads/google-ads-python#486]
In version `14.0.0` of this library a new _required_ configuration parameter has been added. Details for why this parameter was added, and what the options are, can be found in our [Protobuf Messages](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages) documentation. 

For any questions or issues not covered on that page, please leave a comment here or file a new [Issue](https://github.com/googleads/google-ads-python/issues/new/choose).

**Comment by mbaader** [comment]
Hi there,

in the [documentation to the 14.0.0 changes](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages#accessing_protobuf_message_methods) it reads:

_"However, if you want to upgrade to version 14.0.0 **without making code changes**, you can set use_proto_plus to True to avoid breaking interface changes."_

Please clarify: Will our programs that run flawlessly with version 13.x continue to run with version 14.x without code changes or do we have to set this "use_proto_plus" somewhere to True? Because that obviously _would_ include code changes.

An can you please elaborate, _where_ we would have to put this "use_proto_plus" parameter. I can't find [any examples](https://developers.google.com/google-ads/api/docs/samples) that include this parameter.

Regards
Mat

**Comment by BenRKarl** [comment]
@mbaader Great question, thank you. This parameter is configuration-level, so it should be set the same way that you set your developer token, oauth tokens, etc. I've updated our sample `google-ads.yaml` file with an example of how to do this, see #487 

If you're using environment variables the variable name is `GOOGLE_ADS_USE_PROTO_PLUS`

**Comment by mbaader** [comment]
Ty, BenRKarl,

that appears to be working so far.

Regards
Mat

**Comment by BenRKarl** [comment]
Wonderful - thanks for letting me know. We're in the process of updating the linked guide to clarify where the configuration parameter needs to be added.
