### ISSUE TITLE
How to bulk remove ads with Google Ads API?

### ISSUE THREAD

**Issue by elad2109** [googleads/google-ads-python#494]
Hi

I saw this [code][1] for bulk creating ad groups.
I want to write similar code for bulk removing ads.

Is my modification correct?

    def build_ad_removal_sync_operation(customer_id, campaign_id, ad_id):
        resource_name = serviceWrapper.ad_group_ad_service.ad_group_ad_path(customer_id, campaign_id, ad_id)
        ad_group_ad_op1 = serviceWrapper.client.get_type("AdGroupAdOperation")
        ad_group_ad_op1.remove.name = f"Remove ad: {customer_id}/{campaign_id}/{ad_id}"
        ad_group_ad_op1.remove.ad = resource_name
        return ad_group_ad_op1
    
    def send_bulk_mutate_request(customer_id, operations):
        # Issue a mutate request, setting partial_failure=True.
        request = serviceWrapper.client.get_type("MutateAdGroupsAdRequest")
        request.customer_id = customer_id
        request.operations = operations
        request.partial_failure = True
        return serviceWrapper.ad_group_ad_service.mutate_ad_groups(request=request)

Thanks!

  [1]: https://github.com/googleads/google-ads-python/blob/b0403e0891c11f9c8aa54d0c28455c8a0502ccd5/examples/error_handling/handle_partial_failure.py

**Comment by laurachevalier4** [comment]
Hey @elad2109! I think the general approach should work, but I have a couple of corrections. Have a look at the [reference docs](https://developers.google.com/google-ads/api/reference/rpc/v8/AdGroupAdOperation) for AdGroupAdOperation; it looks like the `remove` field on the operation object should be just a string representing the resource name (e.g. `ad_group_ad_op1.remove = resource_name`). The resource name, meanwhile, should use the ad_group_id rather than the campaign_id, which you can see in the [Remove Ad example](https://developers.google.com/google-ads/api/docs/samples/remove-ad) in our docs.

Once those changes have been made, I'd recommend testing this out in a test account to ensure that it behaves in the way you expect. Additionally, you can try running `mutate_ad_groups` with the [`validate_only` field](https://developers.google.com/google-ads/api/reference/rpc/v8/MutateAdGroupAdsRequest#validate_only) set to `True` to see if any errors would be returned.

Hope this helps! Let us know if you have any other questions.
