### ISSUE TITLE
[Feature request] device bid adjustments for campaigns

### ISSUE THREAD

**Issue by Cosbgn** [googleads/google-ads-python#5]
At the moment is possible to add `bid adjustments` for devices only selecting Ad Groups.

It would be very useful if we could do the same for campaigns which at the moment support only `CALL` bid adjustments. 

Is this feature going to be released sometime soon? Thanks!

**Comment by msaniscalchi** [comment]
Hello,

Thanks for submitting a feature request, but it's not something we can implement via this library--the underlying API would need to change in order to add this functionality. For a request to expand API functionality such as this one, please submit your inquiry to the [Google AdWords API Support Forum](https://groups.google.com/forum/#!forum/adwords-api).

Regards,
Mark
