### ISSUE TITLE
Severe performance degradation for some operations in Python 3.10

### ISSUE THREAD

**Issue by Lyrositor** [googleads/google-ads-python#514]
**Describe the bug:** Iterating over any repeated field is considerably slower in Python 3.10 than in Python 3.9.

**Steps to Reproduce:** The following program is a minimal reproduction of the issue:

```python
from timeit import timeit
from google.ads.googleads.v7.resources.types.feed import Feed

feed = Feed()
print(timeit(lambda: list(feed.attributes), number=1000))
```

Running this in Python 3.9 takes **0.009 seconds**. Running this in Python 3.10 takes **7.14 seconds**.

A little bit of profiling has revealed that this seems to be tied to a `deepcopy` operation being performed by the repeated field when type-checking.

**Expected behavior:** The time it takes to iterate over an empty list should remain reasonable.

**Client library version and API version:**
Client library version: 14.0.1
Google Ads API version: v7/v8

No dependencies required besides the Google Ads library.

**Request/Response Logs:** *No requests involved*

 
**Anything else we should know about your project / environment:** *N/A*

**Comment by BenRKarl** [comment]
@Lyrositor - I'm currently working with the protobuf maintainers to address this issue. However I have a workaround for you that should suffice in the meantime. Once they publish a fix I'll update this library to consume the fixed dependency. 

If you want to use Python version 3.10.0 you need to install protobuf version 3.19.0, and you shouldn't need to  set the `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION` flag as it should default to the `cpp` implementation. Any other version of protobuf with Python 3.10.0 will default to the (much slower) `python` implementation.

You will likely see `pip` warnings because this library will be configured to install protobuf > 3.18.0, but you should still be able to use everything just fine. 

I'm going to close this for now, but reopen it if you have any issues with the above workaround, and keep an eye on our releases, once there's a protobuf fix you should be able continue working with Python 3.10.0 without any manual intervention.
