### ISSUE TITLE
Customer match user identifiers format change

### ISSUE THREAD

**Issue by benanbardak** [googleads/google-ads-python#538]
Hi,

I'm trying to create Custom Audiences for Remarketing Campaigns via Google Ads API on Python language.
I'm using this documentation: **https://developers.google.com/google-ads/api/docs/remarketing/audience-types/customer-match#python** and using this code : **https://github.com/googleads/google-ads-python/blob/769ece80ffb3344575d4a357f9dc29da4f107485/examples/remarketing/add_customer_match_user_list.py#L193-L241**

I sent audiences with idfas through API as this code (modified github code block) :

**def _build_offline_user_data_job_operations(client,idfa):
    user_data_with_id_operation = client.get_type(
    "OfflineUserDataJobOperation")
    # to send all idfa of our list 
    for i in idfa:
        user_data_with_id = user_data_with_id_operation.create
        user_identifier_with_id_not_hash = client.get_type("UserIdentifier")
        user_identifier_with_id_not_hash.mobile_id = i     
        user_data_with_id.user_identifiers.append(user_identifier_with_id_not_hash)
    return [
        user_data_with_id_operation ]**

output format : 
![image](https://user-images.githubusercontent.com/50618433/144816060-6f5ef8a1-af38-4813-bfbf-9aafc1c99c1b.png)
      
Output format is correct so this code is working now but I saw  UserData Enforcement in Google Ads API blog.  **(https://ads-developers.googleblog.com/2021/10/userdata-enforcement-in-google-ads-api.html)** 
It is written that the format will changed on 10 January 2022 so my format will be different from correct usage. 

I didn't find any other documentation except this blog for this changing format and reducing number of user identifiers (100000 to 20) How can I change my code for the correct format due to 10 January 2022 ?  Are you going to change customer matching code block for this development ?

Any help would be appreciated.

Thanks in advance.

**Comment by laurachevalier4** [comment]
Hey @benanbardak! The change specified in the blog post is just the limit that is being imposed onto the number of user identifiers that should be in a single [UserData](https://developers.google.com/google-ads/api/reference/rpc/v7/UserData#user_identifiers[]) object. This is how UserData should have been used all along, but now the limit will help to enforce that intended usage. 

So, for instance, if you're currently combining all of your user identifiers, representing multiple different users, into a single `user_data.user_identifiers` list, then you'll instead need to break that up so that you have a distinct `user_data` object (and thus a distinct `user_identifiers` list) for each user; each `user_identifiers` list would have no more than 20 items. Because the [code example](google-ads-python/examples/remarketing/add_customer_match_user_list.py) is capturing two different users, each with their own `user_data` object (and `user_identifiers` lists of length 1), it is already aligned with the requirements announced in that blog post.

Does that answer your question?

**Comment by benanbardak** [comment]
Hi,

Thank you very much for your reply. I think my code block is working correctly. 

I want to ask another question about updating custom audience list.

I can send custom audiences to google ads manager via google ads api. But since our target audience changes every day, I want to update the custom list. When I reviewed the google ads document, I modified the code as follows for update customs. But I could not delete the users in the list. Do you have sample code you can share on this? How can I use the remove_all parameter?

document : https://developers.google.com/google-ads/api/docs/remarketing/audience-types/customer-match#remove_all_data_from_the_list_at_once

```
## remove all functions
create_offline_user_data_job_response = offline_user_data_job_service_client.create_offline_user_data_job(
customer_id=customer_id, job=offline_user_data_job
)
offline_user_data_job_resource_name = create_offline_user_data_job_response.resource_name

print(
“Created an offline user data job with resource name: ”
f"'{offline_user_data_job_resource_name}'."
)

request = client.get_type(“AddOfflineUserDataJobOperationsRequest”)
request.resource_name = offline_user_data_job_resource_name

request.operations = _build_offline_user_data_job_operations(client,idfa)
request.operations.**remove_all** = True
print(request)
request.enable_partial_failure = False
```

Thank you for your interesting.

**Comment by laurachevalier4** [comment]
Hey @benanbardak. When you say _"I could not delete the users in the list"_, do you mean that you're getting a particular error message, and if so can you share that?

Based on the documentation you shared, it looks like you should be [creating an OfflineUserDataJobOperation](https://developers.google.com/google-ads/api/docs/remarketing/audience-types/customer-match#remove_all_data_from_the_list_at_once) object, and setting the `remove_all` field to True. Then, this [operation](https://developers.google.com/google-ads/api/reference/rpc/v9/OfflineUserDataJobOperation) needs to be the first in the list of `operations` supplied to your request object. So your code might look something like this:
```
## YOUR CODE
## remove all functions
create_offline_user_data_job_response = offline_user_data_job_service_client.create_offline_user_data_job(
customer_id=customer_id, job=offline_user_data_job
)
offline_user_data_job_resource_name = create_offline_user_data_job_response.resource_name

print(
“Created an offline user data job with resource name: ”
f"'{offline_user_data_job_resource_name}'."
)

request = client.get_type(“AddOfflineUserDataJobOperationsRequest”)
request.resource_name = offline_user_data_job_resource_name

## MY CHANGES BELOW
# Create the operation.
remove_operation = client.get_type(
    "OfflineUserDataJobOperation"
)
remove_operation.remove_all = True
# The removal operation should be at the front of the list.
request.operations = [remove_operation, <any other operations you need in this request>]

print(request)
request.enable_partial_failure = False
```
This might require some tweaking to fit your use case, but the main thing to note is that you should be setting `remove_all` on the `OfflineUserDataJobOperation`, not on the request's `operations` field. Hope this helps!

**Comment by benanbardak** [comment]
Hi,

Thank you for your quick reply. As you said, I tried to remove it from the list by creating a job operation. But I am getting the following error.

How should I parametrically give the code as a resource name to delete a user from a specific audience? (I'm using the same code you shared with me.)

**Error message :**

```
Created an offline user data job with resource name: 'customers/2146304081/userLists/6993455629'.
resource_name: "customers/2146304081/userLists/6993455629"
operations {
  remove_all: true
}

Request made: ClientCustomerId: 2146304081, Host: googleads.googleapis.com, Method: /google.ads.googleads.v8.services.OfflineUserDataJobService/AddOfflineUserDataJobOperations, RequestId: v88FMWRuev1Se5BnAE7VJg, IsFault: True, FaultMessage: Resource name 'customers/2146304081/userLists/6993455629' is malformed: expected 'customers/{customer_id}/offlineUserDataJobs/{offline_user_data_update_id}'.
```

Thank you for your interest. Have a nice day!  @laurachevalier4

**Comment by laurachevalier4** [comment]
Thanks @benanbardak for sharing those request details. If the resource name that's returned is structured like that ('customers/x/userLists/y'), it looks like you're creating a UserList instead of an OfflineUserDataJob. Please review your code to make sure `offline_user_data_job_service_client` is created by calling `client.get_service("OfflineUserDataJobService")`, and that `create_offline_user_data_job` is returning an instance of [`CreateOfflineUserDataJobResponse`](https://developers.google.com/google-ads/api/reference/rpc/v9/CreateOfflineUserDataJobResponse). If the resource name you provide as `offline_user_data_job_resource_name` is that of an [OfflineUserDataJob]( https://developers.google.com/google-ads/api/reference/rpc/v9/OfflineUserDataJob#resource_name), you should not be getting that error.

**Comment by benanbardak** [comment]
Hi,

Thank you very much for your quick, clear answers and help. Thanks to your suggestions, I deleted the audiences.  
But it took 2 days to delete the 100k list. I also tried deleting a 2k list.  But it also took 2 days to delete the 2k list.
This indicates that the deletion process takes a long time, regardless of audience size. Is there a way to optimize the duration of the deletion? 

Looking forward to your reply, have a nice day ! @laurachevalier4

**Comment by laurachevalier4** [comment]
Hey @benanbardak. How are you measuring the amount of time it takes to delete the list? Is it 48 hours before the list is showing that it contains 0 users? 48 hours until the OfflineUserDataJob [status](https://developers.google.com/google-ads/api/reference/rpc/v9/OfflineUserDataJob#status) is `SUCCESS`? Something else? 

Since this isn't specific to the Python client library, I suggest sending your question to googleadsapi-support@google.com, including (1) an explanation of how you're getting the "2 days" metric per my questions above, and (2) the request ID for the operation where remove_all was set to true. It's possible that the users are getting removed right away, but the numbers are not reflecting that until 48 hours later; you might be able to confirm this if you find that it takes >24 hours to see that the list contains 0 users, and that the OfflineUserDataJob is taking less time than that to complete. I'm not sure if this is expected behavior, but that support alias should be able to help you make that determination provided you give them those details.
