### ISSUE TITLE
Error 400: invalid_request when generating refresh token

### ISSUE THREAD

**Issue by wmpeng** [googleads/google-ads-python#600]
**Describe the bug:**

An errors occured when I try to generate a refresh token according to [OAuth Desktop Application Flow](https://developers.google.com/google-ads/api/docs/client-libs/python/oauth-desktop#step_3_-_generate_a_refresh_token).

```
Error 400: invalid_request

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.

Request details:

The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.

If you’re the app developer, make sure that these request details comply with Google policies.

redirect_uri: urn:ietf:wg:oauth:2.0:oob
```

**Steps to Reproduce:**

```
cd examples/authentication
./authenticate_in_desktop_application.py --client_secrets_path=/path/to/secrets.json
```

**Expected behavior:**

to visit a URL and then finish auth flow.

**Client library version and API version:**
Client library version: /
Google Ads API version: /

google-ads-python (this repo) : tag v 15.0.0
google-auth-oauthlib: 0.5.1

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

**Solution**

Provide a temp solution:

This error is caused by deprecation of ood: https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html?m=1#disallowed-oob .

```
https://github.com/googleapis/google-auth-library-python-oauthlib/blob/f424959f35f164ce272251b4b19384f9d3a76065/google_auth_oauthlib/flow.py#L388-L403
```

The script `./authenticate_in_desktop_application.py` uses `InstalledAppFlow.run_console()`, which should be replaced by `run_local_server()`.

https://github.com/googleads/google-ads-python/blob/c0b02a2a3ee444e5e6a105417e6ffcdba27e7674/examples/authentication/authenticate_in_desktop_application.py#L33-L37

**Comment by BenRKarl** [comment]
Hi @wmpeng - the desktop flow is being phased out and no longer works, we're still working on updating our examples here. You should be able to use the web_flow example using Desktop credentials with one minor change. Try replacing [this line](https://github.com/googleads/google-ads-python/pull/611) with the following:

```py
_REDIRECT_URI = f"http://127.0.0.1:{_PORT}"
```

Let me know if that works for you. Thanks!

**Comment by BenRKarl** [comment]
@wmpeng I'm guessing this worked for you, but if not please re-open this and I'll continue helping.

**Comment by jbrow70** [comment]
Hi @BenRKarl,

We're dealing with this now! We can create a web app but we'd like to create a desktop app. After we did all that, we then searched the issue page here, and it appears others have found workarounds because yeah desktop mode requires loopback now and not manual copy and paste as they deprecated that (today loopback is directly documented). 

We'll try the solution @wmpeng provided above (https://github.com/googleads/google-ads-python/issues/600#:~:text=your%20project%20/%20environment%3A-,Solution,-Provide%20a%20temp). That appears to be a solution in the https://github.com/googleads/google-ads-python/blob/main/examples/authentication/authenticate_in_desktop_application.py.

However I'm curious as to your solution. You mention Try replacing "this line" but that leads to a pull request, and from there I can't figure out what line in the code to replace with what you suggest. Are you talking about replacing some line in https://github.com/googleads/google-ads-python/blob/main/examples/authentication/authenticate_in_web_application.py in the web_flow example to make it work for desktop flow? If so, what is "this line" in that file that needs replaced to make it work for desktop flow?

We want to have multiple solutions in our belt when we try this tomorrow (that's our plan anyway). We're hitting this google adwords api to ads api migration due to adwords api sunsetting at the end of the month so have some speediness to this project (I guess you could call us slackers haha). Like I said, we have web app working (we haven't verified the web app yet as google requires which is somewhat convoluted. needs a youtube video of our use case or something haha), but we'd prefer to use Desktop app for our integration as that's what we were using for adwords api integration and it works well for our use case (plus set up of desktop app is a lot simpler!) 

Thanks for your help and clarification on this matter!

-Jordan

**Comment by BenRKarl** [comment]
Hi @jbrow70 thanks for the question, it looks like I used the wrong link in my previous comment. What I meant was [this line](https://github.com/googleads/google-ads-python/blob/main/examples/authentication/authenticate_in_web_application.py#L46), where the redirect URI is set:

```py
_REDIRECT_URI = f"http://localhost:{_PORT}"
```

Should be changed to:

```py
_REDIRECT_URI = f"http://127.0.0.1:{_PORT}"
```

...because this flow won't work with `localhost` when using the desktop flow.

I also updated my previous comment with the correct URL. Hope this helps, let me know if you have any other issues.

**Comment by jbrow70** [comment]
Ah yeah! Even for our web app try today, we had to change from localhost to 127.0.0.1 (also specify that in the redirect URI in the google ads console under the oauth for web app only). Then it worked there! 

That all makes sense now for the desktop app version. We'll try that tomorrow, thank you!
