### ISSUE TITLE
Issue with ConversionUploadService and UploadCallConversionsRequest client

### ISSUE THREAD

**Issue by nishanthj14** [googleads/google-ads-python#613]
Hi,

We are using this file, https://github.com/googleads/google-ads-python/blob/680a48a68d23490bb63859ac99d61414517a63a0/examples/remarketing/upload_call_conversion.py and also what's documented on google ads api docs, https://developers.google.com/google-ads/api/docs/samples/upload-call-conversion?hl=en as our examples to build out our call conversion upload service.
We've also been in contact with the Google Ads API Team directly via email, and they've directed us to the owners of this client (which is y'all) to help further with this issue. 

I have attached my script (removed sensitive info such as tokens etc.) and whenever I run it, I get this error:
    request.conversions = [call_conversion]
AttributeError: Assignment not allowed to repeated field "conversions" in protocol message object.
 on the line: request.conversions = [call_conversion]

We have tried everything on our end that we can think of atm like having the correct version of the client library and python library but still get this error.

We are on:
Python version
3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
Version info.
sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
and google-ads-python-v.15.0.0
Can you let us know how to fix this error.
[program_1.zip](https://github.com/googleads/google-ads-python/files/8411901/program_1.zip)

Note: Python file is zipped.

Thanks,
Joseph

**Comment by jbrow70** [comment]
Hi @BenRKarl ,

Thanks for your help on this! Your advice got us unstuck on that (the original poster is on my team). We had been working with google ads api team, but they were directing us to y'all (github owners of the python client). That's when we posted this issue!

In retrospect, one thing we'd suggest (The Google Ads API team ask that we direct this request to y'all);

In the readme proto plus section on github (https://github.com/googleads/google-ads-python#protobuf-messages) we suggest adding some clarity around use_proto_plus. It should mention that if one doesn't use the yaml configuration and just tries to initialize GoogleAdsClient() today, without specifying the use_proto_plus parameter, it'll default to use proto plus false. This will potentially lead to unexpected issues when using google ads python client docs as essentially all docs assume you're setting use_proto_plus=true. We spent days going in circles (also working with the Google Ads API team who couldn't provide us the solution and directed us to y'all in the end), and in the end didn't realize this protobuf vs proto-plus nuance. The docs essentially presume you're setting use_proto_plus to true. The docs are set-up that use_proto_plus needs to be set to true. But if one's not careful, since the default is use_proto_plus=False (I'm sure for compatibility reasons) it can lead to a lot of confusion. (especially for folks like us only now migrating from google adwords api to google ads apis--I'm sure there's a lot out there in our shoes or soon will be with google adwords api sunsetting is THIS MONTH. I know we're slackers but it's a combination of technical debt, small team, and too much going on haha). 

As mentioned, we're migrating from google adwords api to google ads api due to the sunsetting of google adwords api at the end of this month. The way we were initializing a GoogleAdClient (so far) is without the configuration yaml. 

We were just doing this initially:

```
GoogleAdsClient(credentials=oauth2_client, developer_token=developer_token,
                               login_customer_id=account_id)
```

And yeah that defaults use_proto_plus to false (as stated in the docs):

(https://github.com/googleads/google-ads-python/blob/bdc334af6303cd63a4b5ff74a984263027cfe3a0/google/ads/googleads/client.py#:~:text=version%3Dversion%2C%20**kwargs))-,def%20__init__,-()

```
  def __init__(
        self,
        credentials,
        developer_token,
        endpoint=None,
        login_customer_id=None,
        logging_config=None,
        linked_customer_id=None,
        version=None,
        http_proxy=None,
        use_proto_plus=False,
    ):
```

which brings us the the issue that my colleague posted originally. 

We changed it to 

```
 GoogleAdsClient(credentials=oauth2_client, developer_token=developer_token,
                               login_customer_id=account_id, use_proto_plus=True)
```
                               
after reading your advice and all worked great/as expected following the documentation. It's just knowing this small but crucial thing is cryptic in the docs.                                

I can understand one wants to set this to false by default for backwards compatibility, but since latter versions of google ads python client version 14+ support proto plus implementation + google ads python client is essentially documenting everything as use_proto_plus=True, it would be good to mention clearly somewhere that the client by default (if not using configuration/yaml and not explicitly setting use_proto_plus upon initializing the Google Ads Client) will just set use_proto_plus to False, and at that point, to be warned that most docs for google ads python client are implemented using Proto-plus and not Protobuf. One can use Protobuf of course and there are valid use cases (we do understand that) but folks should understand that what's documented will have to be tweaked for protobuf implementation. It won't work out of the box with protobuf implementation. 

If just in the readme in the protobuf messages section had like an additional single line like

"Latest docs are implemented using proto plus (use_proto_plus=True). Be warned!" 

I think it would go a long way :) I'm sure others would appreciate it!

-Jordan

**Comment by BenRKarl** [comment]
@jbrow70 thanks for all this feedback! It's really valuable to read all of this.

We do have validations set up that will raise an error if `use_proto_plus` isn't set, however it's only triggered if you use the `load_from_*` constructor methods, not when you initialize the class directly. In fact there are several other configuration [validations](https://github.com/googleads/google-ads-python/blob/main/google/ads/googleads/config.py#L159) that are skipped when constructing the class directly, so I would strongly recommend using a `load_from_*` method. We typically use `load_from_storage` in our [examples](https://github.com/googleads/google-ads-python/tree/main/examples), which will load configuration and oauth credentials from a yaml file, but in your case, since you already have this configuration at runtime, it may be simpler to use [`load_from_dict`](https://github.com/googleads/google-ads-python/blob/main/google/ads/googleads/client.py#L254). 

In any case I'll take a look at our docs and see if I can emphasize that it's important to use a constructor method instead of instantiating the class directly. Thanks again for the feedback!
