### ISSUE TITLE
Does support asyncio?

### ISSUE THREAD

**Issue by toughrogrammer** [googleads/google-ads-python#632]
**What is your question?**

I need to upload large size of customer match list.
I read documentation but I couldn't find reference about asyncio.
Is there way to send request with asyncio?
Or, do I need to use multiprocessing or multithreading?

**Comment by wihl** [comment]
If you have to upload a large number of users, use the [OfflineUserDataJobService](https://developers.google.com/google-ads/api/reference/rpc/v10/OfflineUserDataJobService) instead of asyncio. With a large number of Python objects, performance will be dramatically improved if you [turn off proto-plus](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages#use_cases_for_proto-plus_and_protobuf_messages) with `use_proto_plus = False` in your [config file](https://developers.google.com/google-ads/api/docs/client-libs/python/configuration).
