### ISSUE TITLE
Error with client.get_type()

### ISSUE THREAD

**Issue by Achilles005** [googleads/google-ads-python#684]
[This issue was marked closed](https://github.com/googleads/google-ads-python/issues/683) and I was not able to place my comment.

@BenRKarl 
I tried setting `use_proto_plus` to both True and False but still got the same error.
` "2022-08-06 16:32:03,511012 	l=DEBUG	ip=	m=	msg=Specified type 'StringValue' does not exist in Google Ads API v11"`

`def _map_locations_ids_to_resource_names(self, location_ids):
        build_resource_name = self.client.get_service("GeoTargetConstantService").geo_target_constant_path
        return [build_resource_name(location_id) for location_id in location_ids]

    def _map_keywords_to_string_values(self, keywords):
        keyword_list = []
        for keyword in keywords:
            string_val = self.client.get_type(StringValue)
            string_val.value = keyword
            keyword_list.append(string_val)
        return keyword_list`

**Comment by BenRKarl** [comment]
@Achilles005 indeed it looks like `StringValue` is not present whether proto-plus is set to true or false. This is actually probably because `StringValue` is not used in the API anywhere, thus is not exported by our library. In fact, looking at [this section](https://github.com/googleads/google-ads-python/blob/main/examples/planning/generate_keyword_ideas.py#L101) of the `generate_keyword_ideas` example, the `map_keywords_to_string_values` method is not used at all (we'll get that fixed), so you should ignore this section of the example. To add keywords to your request, you can use the strings directly, no need to convert them to a specific type, see [here](https://github.com/googleads/google-ads-python/blob/main/examples/planning/generate_keyword_ideas.py#L77) for example.
