### ISSUE TITLE
Empty keyword text in MutateAdGroupCriteriaResponse

### ISSUE THREAD

**Issue by Sebadst** [googleads/google-ads-python#729]
**Describe the bug:**
I am adding keywords to an ad group. When reading the result, I find the keyword text to be empty.

**Steps to Reproduce:**
The steps are exactly the ones reported in the sample [here](https://developers.google.com/google-ads/api/samples/add-keywords).
Then I try to read the keyword by reading 
`ad_group_criterion_response.results[0].ad_group_criterion.keyword.text`
but the text is empty

**Expected behavior:**
The keyword text should be the one inserted in my request.

**Client library version and API version:**
Client library version: 18.0.0
Google Ads API version: v11

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

**Comment by BenRKarl** [comment]
@Sebadst by default the API will return _only_ the resource name for newly created entities. If you want to access the information on the newly created object, you can either submit a report request using the resource name from the newly created AdGroupCriterion, or you can set the [`response_content_type`](https://developers.google.com/google-ads/api/reference/rpc/v12/MutateAdGroupCriteriaRequest#response_content_type) field on the request to `MUTABLE_RESOURCE` so that the entire object is returned. Here's a modified snippet of the example you linked to that shows how to do this:

```py
# We initialize the request object outside of the mutate method
request = client.get_type("MutateAdGroupCriteriaRequest")
# Set the customer ID and operations here instead of passing them to the mutate method
request.customer_id = customer_id
request.operations = [ad_group_criterion_operation]
# Explicitly set the response_content_type field,
request.response_content_type = client.enums.ResponseContentTypeEnum.MUTABLE_RESOURCE
ad_group_criterion_response = (
    ad_group_criterion_service.mutate_ad_group_criteria(
        # Pass the entire request object to the mutate method
        request=request
    )
)
```
