### ISSUE TITLE
list_accessible_customers returns default string instead of the actual name of the account

### ISSUE THREAD

**Issue by lichyio** [googleads/google-ads-python#731]
When invoking the list_accessible_customers method, the outcome that is expected is the name of the accessible account + the customer ID, what actually happens is that a default string "customers"returning with a valid Customer ID
so it looks like this ->  "customers/80123123123", the expected result should be something like -> "John ADS/80123123123".

**Steps to Reproduce:**
use the list_accessible_customers method following the given example from the docs - https://github.com/googleads/google-ads-python/blob/1c01c5efaa4bc6edfe5bfa441cce487f3a3f850f/examples/account_management/list_accessible_customers.py#L31-L40

**Expected behavior:**
instead of "customers/80123123123", 
the expected result should be something like -> "John ADS/80123123123".

Google Ads API version: v12

**Comment by BenRKarl** [comment]
Hi @lichyio - this is expected behavior, the [`ListAccessibleCustomers`](https://developers.google.com/google-ads/api/reference/rpc/v12/ListAccessibleCustomersResponse#resource_names[]) method intentionally returns resource names for each accessible customer. If you want to retrieve the [`descriptive_name`](https://developers.google.com/google-ads/api/fields/v12/customer#customer.descriptive_name) - or any other [Customer attribute](https://developers.google.com/google-ads/api/fields/v12/customer) - you will need to submit a subsequent Search query using each of the resource names obtained from `ListAccessibleCustomers`, for example:

```py
    ga_service = client.get_service("GoogleAdsService")

    # Here we use the resource name from the ListAccessibleCustomer method.
    query = f"""
        SELECT
          customer.descriptive_name,
        FROM customer
        WHERE customer.resource_name = {resource_name}"""

    # Issues a search request using streaming.
    stream = ga_service.search_stream(customer_id=customer_id, query=query)

    for batch in stream:
        for row in batch.results:
            print(
                f"Customer with name {row.customer.descriptive_name} was found."
            )
```
