### ISSUE TITLE
What is the best approach to avoid SQL injection using the library?

### ISSUE THREAD

**Issue by Luiz-Cruz** [googleads/google-ads-python#732]
Hello everyone. 

I would like to know if there is any approach that could be taken to avoid SQL injection in query calls to the Google Ads API in Python, for example the code below:

```
googleads_service = self.client.get_service("GoogleAdsService")
 
        query = f"""
            SELECT
                customer_client.id
            FROM
                customer_client
            WHERE
                customer_client.id IN ({account_ids}) 
            """
response = googleads_service.search(customer_id=req_customer_id, query=query)
```

Is there any indication how to avoid an sql injection in the following example?

thank you in advance.

**Comment by BenRKarl** [comment]
@Luiz-Cruz the query language we use isn't SQL, it's called [`GAQL`](https://developers.google.com/google-ads/api/docs/query/overview), and is thus not susceptible to the same types of injection attacks as SQL because it's range of functionality is much smaller. Specifically, there is no query in GAQL that would allow you to write or update data, it's used **only** for reads.

Hope that helps, let me know if you have any more specific questions.
