### ISSUE TITLE
Is error code for CONVERSION_NOT_FOUND is correct?

### ISSUE THREAD

**Issue by egor187** [googleads/google-ads-python#741]
Hello, I'm trying to handle CONVERSION_NOT_FOUND error from Google Ads while making ConversionAdjustment. 

Using lib version == 19.0.0

In Google reference this type of GoogleAdsErrors contains this description: "**A conversion for the supplied combination of conversion action and conversion identifier could not be found.**"  (https://developers.google.com/google-ads/api/reference/rpc/v12/ConversionAdjustmentUploadErrorEnum.ConversionAdjustmentUploadError#conversion_not_found).

In source code (/google/ads/googleads/v12/errors/types/conversion_adjustment_upload_error.py) this type of error numbered by code 5 (on 41 line).

But when i make api call from calling code I recieve code 3 (NOT 5) with **MOST** exactly the same description of error:

```
partial_failure_error {
  code: 3
  message: "A conversion for the supplied conversion action and conversion identifier pair could not be found., at conversion_adjustments[0].order_id"
  details {
    type_url: "type.googleapis.com/google.ads.googleads.v12.errors.GoogleAdsFailure"
    value: "\n\237\001\n\003\230\007\005\022bA conversion for the supplied conversion action and conversion identifier pair could not be found.\032\n*\01010363648\"(\022\032\n\026conversion_adjustments\030\000\022\n\n\010order_id"
  }
}
results {
}
```
Difference: Google api reference notes about '... combination of conversion action and conversion identifier' and api response notes about '... conversion action and conversion identifier'.

BTW, source code for error code 3 defines 'INVALID_CONVERSION_ACTION' error which has a completely different description from Google api reference.

QUESTIONS: 1. Based on the given error descriptions, are they the same thing? 2. If 'YES', is this valid lib behavior error codes? And how correctly handle CONVERSION_NOT_FOUND error: by error code or by parsing error description from api response (on my opinion, don't think this option is suitable).

**Comment by BenRKarl** [comment]
@egor187 It looks like you're trying to act on `partial_errors` returned by the API. If so, I would take a look at [this code example](https://github.com/googleads/google-ads-python/blob/main/examples/error_handling/handle_partial_failure.py) where we show how to process these types of errors.

To answer your questions:

* The object associated with the `partial_failure_error` field above is an instance of the generic [`google.rpc.Status`](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto) proto, so the `code` field there actually refers to one of the codes listed [here](https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto#L58), specifically `3` refers to `INVALID_ARGUMENT`, which is true generally, and as specific as this class can get.
* The discrepancy between the error messages appears to be due to an oversight and/or typo. The description in our documentation is actually dynamically generated using the comments from the proto definition, (for [example](https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v12/errors/conversion_adjustment_upload_error.proto#L52)), and the actual error message is derived from a slightly different set of non-public proto definitions. I'll file a bug to have these updated to be the same. 

If your goal is to write code that differentiates errors returned by `partial_failure`, you should actually find the serialized `GoogleAdsFailure` message attached to the `details.value` field, specifically this string:

`"\n\237\001\n\003\230\007\005\022bA conversion for the supplied conversion action and conversion identifier pair could not be found.\032\n*\01010363648\"(\022\032\n\026conversion_adjustments\030\000\022\n\n\010order_id"`

You can see how to deserialize this value by looking at [this section](https://github.com/googleads/google-ads-python/blob/main/examples/error_handling/handle_partial_failure.py#L173-L177) of our example. After doing so you can see the error looks like this:

```
errors {
  error_code {
    conversion_adjustment_upload_error: CONVERSION_NOT_FOUND
  }
  message: "A conversion for the supplied conversion action and conversion identifier pair could not be found."
  trigger {
    string_value: "10363648"
  }
  location {
    field_path_elements {
      field_name: "conversion_adjustments"
      index: 0
    }
    field_path_elements {
      field_name: "order_id"
    }
  }
}
```

And you can find the data you're looking for by doing this:

```py
GoogleAdsFailure = type(failure_message)
failure_object = GoogleAdsFailure.deserialize(error_detail.value)
error_code = err.errors[0].error_code
oneof_field_name = type(code).pb(code).WhichOneof("error_code")
enum = getattr(error_code, oneof_field_name)
print(enum.name)
>>> 'CONVERSION_NOT_FOUND'
print(enum.value)
>>> 5
```
