### ISSUE TITLE
Including `segments.date` doesn't reveal dates

### ISSUE THREAD

**Issue by n0rlant1s** [googleads/google-ads-python#749]
I just started working with the Google Ads API with this library and am interested in getting various data points (clicks, impressions, etc.) with specific information for **each** date, for example: {'2023-02-01': {'clicks': 123, 'impressions': 2000} etc.

I got the API set up, but it isn't returning the date -- see the difference between Query 1 and Query 2 below. 

**Query 1 (Without segments.date)**
```
SELECT campaign.name FROM campaign WHERE segments.date DURING LAST_30_DAYS
```
returns 
```
SearchPager<results {
  campaign {
    resource_name: "customers/4031777845/campaigns/19706223980"
    name: "Example Campaign"
  }
}
field_mask {
  paths: "campaign.name"
}
>
```

**Query 2 (With segments.date)**
```
SELECT campaign.name, segments.date FROM campaign WHERE segments.date DURING LAST_30_DAYS
```
returns
```
SearchPager<field_mask {
  paths: "segments.date"
  paths: "campaign.name"
}
```
**Question: What am I doing wrong?**

**Comment by BenRKarl** [comment]
@n0rlant1s the issue here is your second query doesn't request any data that can be segmented (e.g. `metrics`), so the response is empty. If you added `metrics.impressions` to this query then it would show you the breakdown of impressions by day, however in this specific case that response will also be empty because this campaign doesn't have any impressions. Once this, or another campaign, accrues some metrics then you should be able to segment them normally. 

In general your approach here looks correct. If you haven't already I would recommend reading our [reporting guide](https://developers.google.com/google-ads/api/docs/reporting/overview), specifically the section on [segmentation](https://developers.google.com/google-ads/api/docs/reporting/segmentation) to learn more about how everything works, as there are some other common pitfalls with segmentation.
