### ISSUE TITLE
Request with ID "AVZ6lLU3qeXrm-6vLgdX1A" failed with status "INVALID_ARGUMENT" !

### ISSUE THREAD

**Issue by OmPrakash707** [googleads/google-ads-python#764]
Request made: ClientCustomerId: XXXXXXXXXX, Host: googleads.googleapis.com, 
Method: /google.ads.googleads.v13.services.AdGroupService/MutateAdGroups, 
RequestId: AVZ6lLU3qeXrm-6vLgdX1A, 
IsFault: True, 
FaultMessage: Resource was not found.

Request with ID "AVZ6lLU3qeXrm-6vLgdX1A" failed with status "INVALID_ARGUMENT" and includes the following errors:
Error with message "Resource was not found.".
On field: operations
On field: update
On field: resource_name

Why i am getting this error ?

**Comment by BenRKarl** [comment]
Hi @OmPrakash707 - using the Request ID I can see that the request is trying to update an ad group that does not exist. The customer ID used in the request does not own any campaigns or ad groups, hence the resource name is invalid. Is it possible that you intended to make the request against a different client account? 

Since this is more of an API issue and not specific to this library, if you have any follow up questions would you please reach out to  this [support page](https://developers.google.com/google-ads/api/support)?

**Comment by OmPrakash707** [comment]
Hi Ben Karl ,
in place of customer-ID I am using login-customer-ID.
Is this the cause of the issue?
