### ISSUE TITLE
Method generate_historical_metrics from KeywordPlanService doesn't work since v21.0

### ISSUE THREAD

**Issue by MaxBarbet** [googleads/google-ads-python#782]
**Describe the bug:**
Since I upgraded my environment to google.ads v21 the method generate_historical_metrics from the KeywordPlanService doesn't work and print this issue :

response = keyword_plan_service.generate_historical_metrics(
AttributeError: 'KeywordPlanServiceClient' object has no attribute 'generate_historical_metrics'

**Steps to Reproduce:**
The basic use case script encounters this error and can be fin here :
https://github.com/googleads/google-ads-python/blob/0739716d5bea93f6242a4a8191419caa6a0b5b0c/examples/planning/generate_historical_metrics.py

**Expected behavior:**
If this is on purpose, a changelog when routes are deleted would be great :)

**Comment by BenRKarl** [comment]
@MaxBarbet which version of the API are you using? If it's v14 then this is expected, because this service has been deprecated in favor of plannless alternatives. See [this blog post](https://ads-developers.googleblog.com/2023/04/ad-group-and-keyword-forecasts-being.html) and take a look at the updated [Keyword Planning guide](https://developers.google.com/google-ads/api/docs/keyword-planning/overview) for up-to-date documentation.
