### ISSUE TITLE
AIP : Naming conventation issue

### ISSUE THREAD

**Issue by garuna-m6** [googleads/google-ads-python#831]
**Describe the bug:**
According to the https://google.aip.dev/ , request proto 
https://github.com/googleads/google-ads-python/blob/3000f181103cdee4379b3f671e0bbca64d101894/google/ads/googleads/v15/services/types/keyword_plan_idea_service.py#L64. (class GenerateKeywordIdeasRequest)
and 
response proto https://github.com/googleads/google-ads-python/blob/3000f181103cdee4379b3f671e0bbca64d101894/google/ads/googleads/v15/services/types/keyword_plan_idea_service.py#L296 (class GenerateKeywordIdeaResponse)
should follow same convention so why Ideas in one and Idea in another

**Expected behavior:**
Both should follow same naming convention

**Client library version and API version:**
Client library version: 22.1.0 
Google Ads API version: v15

**Comment by BenRKarl** [comment]
@garuna-m6 - thanks for pointing this out. This change will need to be made at the API level and can only be made for an upcoming major version. I've filed a bug internally to try to get this updated for v16, but I'm not sure if it will be included or not. If not hopefully it will make it into the following major version. Note that it can't be fixed in v15 or any previous versions. To know when the change has been made in the API, keep an eye on our [documentation](https://developers.google.com/google-ads/api/docs/release-notes).
