### ISSUE TITLE
DEADLINE_EXCEEDED

### ISSUE THREAD

**Issue by Olmer1st** [googleads/google-ads-python#87]
Hi,
When using search sometime DEADLINE_EXCEEDED exception happens with failure instead retry. Looks like https://github.com/googleads/google-ads-python/blob/master/google/ads/google_ads/v1/services/google_ads_service_client_config.py
retry_codes_name should be  "idempotent",isn't it?

**Comment by mbaader** [comment]
Hi Olmer1st,

thanks for pointing this out. That might be the answer, why me and others keep getting the occational 504 Deadline Exceeded error while I never got this error before while using the AdWords API:
https://groups.google.com/forum/#!searchin/adwords-api/Deadline$20Exceeded%7Csort:date

**Comment by BenRKarl** [comment]
@Olmer1st thanks for posting this, and apologies for my delayed response. I'm looking into why it's configured this way and will follow up with more info. I see that [Ruby](https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/v1/services/google_ads_service_client_config.json) is also configured in the same way so I assume it's intentional.

**Comment by mbaader** [comment]
Hi Ben Karl, 

a short comment of my side: 14 days ago, I have changed these two lines in my local copy of the python library to

`"retry_codes_name": "idempotent",`

 and since then I never received this DEADLINE_EXCEEDED error anymore.

Regards
Mat

**Comment by BenRKarl** [comment]
@mbaader thank you for the info! I'm starting to feel like this might actually be a flaw in the configuration, I'm investigating and will keep you posted in this thread.

**Comment by BenRKarl** [comment]
@mbaader @Olmer1st I just posted a PR that should resolve this issue, thank you for bringing this up! https://github.com/googleads/google-ads-python/pull/124
