### ISSUE TITLE
Support MyPy

### ISSUE THREAD

**Issue by rusheb** [googleads/google-ads-python#97]
When I import a module I get a MyPy error from this library, e.g. 
`Cannot find module named google.ads.google_ads.client`

Possible solutions:
* Add typing to the client library
* Generate [MyPy stub files](https://mypy.readthedocs.io/en/latest/stubs.html)

Can these be autogenerated easily? I'd be happy to help set this up if not.

**Comment by j-walker23** [comment]
I would give up my first born to have this in this library

**Comment by BenRKarl** [comment]
@rusheb Thanks for the suggestion. I don't know a ton about how MyPy works. It appears as though the issue has to do with finding the module in path. Do you know if there's a way to resolve this problem without adding functionality specific to MyPy?

**Comment by j-walker23** [comment]
@BenRKarl My guess as to @rusheb specific error is because there is no `__init__.py` in `google/ads` folder. And it looks like MyPy doesn't work yet with how google usually packages python libs using namespaces.
https://github.com/python/mypy/issues/5759

What i would give my first born for is to have type hints on resources/services/operations and such.
That would be a night and day difference in difficulty integrating this api. 

But looking at how this is built I'm not even sure that its possible without duplicating all definition files. Maybe they could be worked into the proto files where all the `DescriptorField`s are.

 I don't think we can ever use type inference when getting types from string names like `client.get_type('CustomerOperation')`.

So while it would be very nice, i'm guessing you have a mill more important things to do.

**Comment by BenRKarl** [comment]
@j-walker23 Thanks for the explanation. Yes unfortunately I believe the way in which types and services are exported and retrieved by the client makes it difficult for inference to happen. The current design saves us a lot of maintenance time because the services/types are generated from proto, and I don't think we'd trade one for the other at this point. However I'll keep this problem in mind as I agree it would be really nice, perhaps there's a way to have both.

P.S. @rusheb - please feel free to make contributions to this repository! Pull requests are welcome and encouraged!

**Comment by j-walker23** [comment]
@BenRKarl That makes sense, I figured the proto makes google level stuff, especially crazy big ads api, way easier. Now that I understand the API patterns better its not nearly as bad. Thanks for the response.

**Comment by henribru** [comment]
> I don't think we can ever use type inference when getting types from string names like `client.get_type('CustomerOperation')`.

This will actually be possible in Python 3.8 using literal types. https://www.python.org/dev/peps/pep-0586/

**Comment by j-walker23** [comment]
@henribru best github notification of my life

**Comment by j-walker23** [comment]
@henribru have you tried doing this? The dropbox tip?
I'm having a hard time.

**Comment by henribru** [comment]
@BenRKarl What are your thoughts on including auto-generated (using `mypy-protobuf`) type stubs in this repository? I've got that working with a little script to generate all the stub files.

If you'd rather not include this I'm planning to publish a stub package on PyPi instead.

**Comment by j-walker23** [comment]
That is amazing. Will the script be on a repo? I am super curious what that
looks like.

**Comment by henribru** [comment]
@j-walker23 The script's pretty simple, it just finds all the compiled protobuffs in this repo, then finds the corresponding originals in https://github.com/googleapis/googleapis and calls `protoc` for each one with the `--mypy_out` parameter. Afterwards it fixes some imports and moves things around to fit the structure of this repo.

It's kinda messy though, so I should clean it up a bit ...

**Comment by j-walker23** [comment]
@henribru thanks for the response. I would love to see it if ever possible. I never knew the correct arguments to `protoc` which made the whole thing a failure.

@BenRKarl Do you think putting this in the repo is an option. The amount of value gained from this for python devs using this lib would be astronomical.

**Comment by henribru** [comment]
Well, since I didn't get a reply I just went ahead and published a stub package: https://pypi.org/project/google-ads-stubs/

Sadly inference isn't working (read the caveats section).

**Comment by j-walker23** [comment]
@henribru Seriously, thank you for the time spent on it. I'm starting on it right now and am so happy!

**Comment by j-walker23** [comment]
@henribru thanks again. This has been super nice.
Any chance you could put the script you used visible anywhere? No biggie if not. I'm just really curious what it looks like since my failed attempts ruined it.

@BenRKarl Have you had a chance to look at this yet? This would be so huge for any newcomers to the api. Because, it's rough to start.

**Comment by henribru** [comment]
@j-walker23 Sorry it's so messy: https://gist.github.com/henribru/a299ca8efd49f7eb1ab0122a1baefa2f

**Comment by j-walker23** [comment]
@henribru You're the man. Thank you.
